# MOHIM raw + mean-centered motif dataset and stem-wise threshold diagnostics

음원을 source 단위로 한 번 분리해 dataset stem과 앞 30초의 모든 4마디 후보 진단 결과를 함께 저장합니다.

## 0. Drive와 mean-centering 브랜치 준비

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import os
import subprocess

REPOSITORY = 'https://github.com/youhan200203/MOHIM.git'
BRANCH = 'codex/occurrence'
REPO_DIR = Path('/content/MOHIM')
if not (REPO_DIR / '.git').is_dir():
    subprocess.run(['git', 'clone', '-b', BRANCH, REPOSITORY, str(REPO_DIR)], check=True)
else:
    subprocess.run(['git', 'fetch', 'origin', BRANCH], cwd=REPO_DIR, check=True)
    subprocess.run(['git', 'switch', BRANCH], cwd=REPO_DIR, check=True)
    subprocess.run(['git', 'pull', '--ff-only', 'origin', BRANCH], cwd=REPO_DIR, check=True)
os.chdir(REPO_DIR)
print('repository:', REPO_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
repository: /content/MOHIM

In [ ]:
%pip install -q -r requirements.txt
%pip install -q --no-deps "beat-this @ git+https://github.com/CPJKU/beat_this.git"

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

## 1. 실험 경로와 범위

In [ ]:
MAX_SONGS = 3000
DATA_SOURCE = 'billboard'  # 'songs' 또는 'billboard'
FORCE_REPROCESS = True
DEVICE = 'cuda'
DEMUCS_BATCH_SIZE = 8
MOTIF_WORKERS = 12
DEMUCS_SHIFTS = 0
AUDIO_FORMAT = 'flac'
MOTIF_BARS = 4
MOTIF_SEARCH_SECONDS = 30.0
MIN_ACTIVE_RATIO = 0.65
MAX_ONSET_CHROMA_DIFFERENCE = 0.40
MIN_ONSET_SIMILARITY = 0.54
MIN_PITCH_CLASS_SPAN = 0.25
MIN_MEAN_CENTERED_SIMILARITY = 0.25
MIN_ONSET_VARIATION = 0.25
SIMILARITY_MODE = 'raw_gate_mean_centered_rank_v1'
MIN_NEXT_BAR_SCORE_GAIN = 0.05

BAR_ALIGNMENT_SCORE_KEYS = (
    'onset_similarity',
    'chroma_similarity',
    'mean_centered_onset_similarity',
    'mean_centered_chroma_similarity',
)

SONGS_DIR = Path('/content/drive/MyDrive/MOHIM/songs')
BILLBOARD_DATASET_DIR = Path('/content/drive/MyDrive/MOHIM/billboard_pop_dataset')
MOTIF_DATASET_DIR = Path('/content/drive/MyDrive/MOHIM/motif_dataset_mean_centered')
MOTIF_VERSION_PATH = MOTIF_DATASET_DIR / '.mohim_motif_version'
SONGS_STEM_DIR = Path('/content/drive/MyDrive/MOHIM/songs_stem_dataset')
DIAGNOSTIC_DIR = Path('/content/drive/MyDrive/MOHIM/motif_stem_diagnostics_mean_centered')
BEAT_CHECKPOINT = Path('/content/checkpoints/beat_this_final0.ckpt')
AUDIO_EXTENSIONS = {'.aac', '.flac', '.m4a', '.mp3', '.ogg', '.wav', '.webm'}

assert DATA_SOURCE in {'songs', 'billboard'}
MOTIF_DATASET_DIR.mkdir(parents=True, exist_ok=True)
SONGS_STEM_DIR.mkdir(parents=True, exist_ok=True)
DIAGNOSTIC_DIR.mkdir(parents=True, exist_ok=True)

## 1-1. `songs` 폴더 입력

`DATA_SOURCE = 'songs'`일 때만 실행되며 파일명을 곡 제목으로 사용합니다.

In [ ]:
if DATA_SOURCE == 'songs':
    song_paths = sorted(
        path for path in SONGS_DIR.iterdir()
        if path.is_file() and path.suffix.lower() in AUDIO_EXTENSIONS
    )[:MAX_SONGS]
    songs = [
        {
            'track_id': path.stem,
            'artist': '',
            'title': path.stem,
            'audio_path': path,
        }
        for path in song_paths
    ]

## 1-2. Billboard dataset 입력

`DATA_SOURCE = 'billboard'`일 때 `billboard_pop_dataset/tracks.json`과 `audio` 폴더에서 실제 음원이 있는 곡을 최대 10개 가져옵니다.

In [ ]:
if DATA_SOURCE == 'billboard':
    from mohim.dataset import index_audio_files, load_local_tracks, resolve_audio_path

    tracks_json = BILLBOARD_DATASET_DIR / 'tracks.json'
    audio_dir = BILLBOARD_DATASET_DIR / 'audio'
    assert tracks_json.is_file(), f'tracks.json이 없습니다: {tracks_json}'
    assert audio_dir.is_dir(), f'음원 폴더가 없습니다: {audio_dir}'

    tracks = load_local_tracks(tracks_json, require_lyrics=True)
    audio_index = index_audio_files(audio_dir)
    songs = []
    for track in tracks:
        audio_path = resolve_audio_path(track, audio_index)
        if audio_path is None:
            print(f'[skip] 음원 없음: {track.artist} - {track.title}')
            continue
        songs.append({
            'track_id': track.track_id,
            'artist': track.artist,
            'title': track.title,
            'audio_path': audio_path,
            'track': track,
        })
        if len(songs) >= MAX_SONGS:
            break
    song_paths = [song['audio_path'] for song in songs]

## 1-3. 선택한 입력 확인

In [ ]:
assert songs, f'사용 가능한 음원이 없습니다: {DATA_SOURCE}'
assert len(songs) == len(song_paths)
print(f'data source: {DATA_SOURCE}')
print('songs:', len(songs))
for song in songs:
    label = f"{song['artist']} - {song['title']}" if song['artist'] else song['title']
    print('-', label)

data source: billboard
songs: 2129
- 2 Pistols Featuring T-Pain & Tay Dizm - She Got It
- 21 Savage - Redrum
- 2AM Club - Worry About You
- 3 Doors Down - It's Not My Time
- 3OH!3 - Don't Trust Me
- 3OH!3 - Double Vision
- 3OH!3 Featuring Ke$ha - My First Kiss
- 5 Seconds of Summer - Amnesia
- 5 Seconds of Summer - Complete Mess
- 5 Seconds of Summer - Easier
- 5 Seconds of Summer - Hey Everybody!
- 5 Seconds of Summer - Me Myself & I
- 5 Seconds of Summer - Old Me
- 5 Seconds of Summer - She Looks So Perfect
- 5 Seconds of Summer - She's Kinda Hot
- 5 Seconds of Summer - Teeth
- 5 Seconds of Summer - Want You Back
- 5 Seconds of Summer - What I Like About You
- 5 Seconds of Summer - Youngblood
- 50 Cent Featuring Justin Timberlake & Timbaland - Ayo Technology
- 50 Cent Featuring Eminem & Adam Levine - My Life
- 88rising & Joji & Jackson Wang Featuring Swae Lee &Major Lazer - Walking
- A Boogie wit da Hoodie - Look Back At It
- A Great Big World & Christina Aguilera - Say Something
- A Great Big World Featuring FUTURISTIC - Hold Each Other
- Acraze Featuring Cherish - Do It To It
- Adam Lambert - Ghost Town
- Adam Lambert - If I Had You
- Adam Lambert - Whataya Want From Me
- Addison Rae - Diet Pepsi
- Addison Rae - Fame Is A Gun
- Adele - Easy On Me
- Adele - Hello
- Adele - Oh My God
- Adele - Rolling In The Deep
- Adele - Rumour Has It
- Adele - Send My Love (To Your New Lover)
- Adele - Set Fire To The Rain
- Adele - Skyfall
- Adele - Someone Like You
- Adele - Water Under The Bridge
- Adele - When We Were Young
- Afrojack Featuring Chris Brown - As Your Friend
- Afrojack Featuring Mike Taylor - SummerThing!
- Afrojack Featuring Eva Simons - Take Over Control
- Afrojack Featuring Wrabel - Ten Feet Tall
- AJ Mitchell - All My Friends
- AJ Mitchell & Ava Max - Slow Dance
- AJ Mitchell - Stop
- AJR - Bang!
- AJR - I'm Ready
- AJR Featuring Rivers Cuomo - Sober Up
- AJR - The Big Goodbye
- AJR - Way Less Sad
- AJR - Weak
- AJR - World's Smallest Violin
- AJR - Yes, I'm A Mess
- Akon - Akon's Beautiful Day
- Akon - Angel
- Akon Featuring Colby O'Donis & Kardinal Offishall - Beautiful
- Akon - Right Now (Na Na Na)
- Alec Benjamin - Oh My God
- Alessia Cara - Growing Pains
- Alessia Cara - Here
- Alessia Cara - Out Of Love
- Alessia Cara - Rooting For You
- Alessia Cara - Scars To Your Beautiful
- Alessia Cara - Sweet Dream
- Alessia Cara - Trust My Lonely
- Alessia Cara - Wild Things
- Alesso, Marshmello & James Bay - Chasing Stars
- Alesso Featuring Tove Lo - Heroes (We Could Be)
- Alex Clare - Too Close
- Alex Warren - Burning Down
- Alex Warren - Carry You Home
- Alex Warren - Fever Dream
- Alex Warren - Ordinary
- AleXa - Wonderland
- Alexandra Stan - Mr. Saxobeat
- Ali Gatie - What If I Told You That I Love You
- Alice Merton - No Roots
- Alicia Keys - Like You'll Never See Me Again
- Alicia Keys - No One
- Alicia Keys - Underdog
- All Time Low - I Feel Like Dancin'
- All Time Low Featuring Blackbear - Monsters
- Ally Brooke Featuring A Boogie wit da Hoodie - Lips Don't Lie
- Ally Brooke Featuring Tyga - Low Key
- almost monday - Can't Slow Down
- Aloe Blacc - The Man
- American Authors - Best Day Of My Life
- Amine - Caroline
- Andy Grammer - Honey, I'm Good.
- Andy Grammer - Keep Your Head Up
- Anitta - Boys Don't Cry
- Anitta Featuring Saweetie - Faking Love
- Anna Kendrick - Cups (Pitch Perfect's When I'm Gone)
- Anne-Marie - 2002
- Anne-Marie - Alarm
- Ant Saunders - Yellow Hearts
- A R Rahman & The Pussycat Dolls Featuring Nicole Scherzinger - Jai Ho! (You Are My Destiny)
- Ariana Grande - 7 Rings
- Ariana Grande - Break Up With Your Girlfriend, I'm Bored
- Ariana Grande - Breathin
- Ariana Grande - Dangerous Woman
- Ariana Grande - Focus
- Ariana Grande - God Is A Woman
- Ariana Grande - Hate That I Made You Love Me
- Ariana Grande - Into You
- Ariana Grande, Miley Cyrus & Lana Del Rey - Don't Call Me Angel (Charlie's Angels)
- Ariana Grande - No Tears Left To Cry
- Ariana Grande - One Last Time
- Ariana Grande - Petal
- Ariana Grande - Popular
- Ariana Grande - Positions
- Ariana Grande - pov
- Ariana Grande - Santa Tell Me
- Ariana Grande Featuring Nicki Minaj - Side To Side
- Ariana Grande - Thank U, Next
- Ariana Grande - The Boy Is Mine
- Ariana Grande - Twilight Zone
- Ariana Grande - We Can't Be Friends (Wait For Your Love)
- Ariana Grande - Yes, And?
- Arizona Zervas - Roxanne
- Arlissa & Jonas Blue - Hearts Ain't Gonna Lie
- Armani White - Billie Eilish.
- Armin van Buuren Featuring Trevor Guthrie - This Is What It Feels Like
- Artemas - I Like The Way You Kiss Me
- Artists Stand Up To Cancer - Just Stand Up!
- Asher Roth - I Love College
- Ashley Tisdale - He Said She Said
- Ashnikko - Daisy
- ATARASHII GAKKO! - Hello
- Auburn Featuring Iyaz - La La La
- Audien Featuring Lady Antebellum - Something Better
- Audrey Hobert - Sue Me
- Audriix - Where The Boys Are
- Austin Mahone Featuring Pitbull - Mmm Yeah
- Austin Mahone - Say Somethin
- Austin Mahone - What About Love
- Ava Max - Kings & Queens
- Ava Max - Maybe You're The Problem
- Ava Max - Million Dollar Baby
- Ava Max - My Head And My Heart
- Ava Max - Sweet But Psycho
- Avenue Beat - F2020
- Avicii - Hey Brother
- Avicii - Levels
- Avicii - Wake Me Up!
- Avril Lavigne - Here's To Never Growing Up
- Avril Lavigne - Hot
- Avril Lavigne Featuring Blackbear - Love It When You Hate Me
- Avril Lavigne - Smile
- Avril Lavigne - What The Hell
- Avril Lavigne - Wish You Were Here
- AWOLNATION - Sail
- Axwell & Ingrosso Featuring Kid Ink - I Love You
- Baauer - Harlem Shake
- Baby Bash Featuring T-Pain - Cyclone
- Baby Bash Featuring Sean Kingston - What Is It
- Backstreet Boys - Don't Go Breaking My Heart
- Bad Bunny & Jhay Cortez - Dakiti
- Bad Bunny - DTMF
- Bad Bunny - EOO
- Bad Meets Evil Featuring Bruno Mars - Lighters
- Bastille - Good Grief
- Bastille - Pompeii
- Bazzi - I Like That
- Bazzi - Mine
- Bazzi - Paradise
- Bazzi - Young & Alive
- BC Jean - Just A Guy
- Bea Miller - Young Blood
- Beach Weather - Sex, Drugs, Etc.
- Bebe Rexha & Florida Georgia Line - Meant To Be
- Bebe Rexha Featuring Doja Cat - Baby, I'm Jealous
- Bebe Rexha - Heart Wants What It Wants
- Bebe Rexha - I Can't Stop Drinking About You
- Bebe Rexha - I Got You
- Bebe Rexha - I'm A Mess
- Bebe Rexha - Last Hurrah
- Bebe Rexha Featuring Nicki Minaj - No Broken Hearts
- Bebe Rexha - Sacrifice
- Bebe Rexha Featuring Lil Wayne - The Way I Are (Dance With Somebody)
- Bebe Rexha - You Can't Stop The Girl
- Becky G - Break A Sweat
- Becky G - Can't Stop Dancin'
- Becky G - Shower
- Bella Kay - Iloveitiloveitiloveit
- Bella Poarch - Build A Bitch
- Belly Featuring The Weeknd - Might Not
- Ben Rector - Brand New
- Benny Blanco & Calvin Harris - I Found You
- Benson Boone - Beautiful Things
- Benson Boone - Ghost Town
- Benson Boone - In The Stars
- Benson Boone - Mr Electric Blue
- Benson Boone - Mystical Magical
- Benson Boone - Slow It Down
- Benson Boone - Sorry I'm Here For Someone Else
- Benson Boone - The Time Of My Life
- Beyonce - Best Thing I Never Had
- Beyonce - Break My Soul
- Beyonce - Countdown
- Beyonce - Cuff It
- Beyonce - Halo
- Beyonce - If I Were A Boy
- Beyonce - Run The World (Girls)
- Beyonce - Sorry
- Beyonce - Sweet Dreams
- BIBI & Jackson Wang - Feeling Lucky
- Big Boi - All Night
- Big Sean - Bounce Back
- Big Sean Featuring Chris Brown - My Last
- Big Time Rush - Boyfriend
- Big Time Rush - Windows Down
- BigXthaPlug Featuring Bailey Zimmerman - All The Way
- Billie Eilish - All The Good Girls Go To Hell
- Billie Eilish - Bad Guy
- Billie Eilish - Birds Of A Feather
- Billie Eilish - Everything I Wanted
- Billie Eilish - Happier Than Ever
- Billie Eilish - Lunch
- Billie Eilish - My Future
- Billie Eilish - NDA
- Billie Eilish - Therefore I Am
- Billie Eilish - What Was I Made For?
- Billie Eilish - When The Party's Over
- Billie Eilish - Wildflower
- Billie Eilish - Your Power
- Bizarrap & Shakira - Bzrp Music Sessions, Vol. 53
- Black Eyed Peas, Anitta & El Alfa - Simply The Best
- Black Eyed Peas Featuring Saweetie & Lele Pons - Hit It
- Black Eyed Peas, Shakira + David Guetta - Don't You Worry
- Blackbear - Do Re Mi
- Blackbear - Hot Girl Bummer
- Blackbear - Queen Of Broken Hearts
- BLACKPINK - Pink Venom
- Blanco Brown - The Git Up
- Blue October - Calling You
- Blxst & Tyga Featuring Ty Dolla $ign - Chosen
- B.o.B Featuring Taylor Swift - Both Of Us
- B.o.B Featuring Priscilla - John Doe
- B.o.B Featuring Rivers Cuomo - Magic
- B.o.B Featuring Bruno Mars - Nothin' On You
- B.o.B - So Good
- Bonnie McKee - American Girl
- Boys Like Girls - Heart Heart Heartbreak
- Boys Like Girls - Hero/Heroine
- Boys Like Girls - Love Drunk
- Boys Like Girls - Thunder
- Boys Like Girls Featuring Taylor Swift - Two Is Better Than One
- Brandy - Right Here (Departed)
- Breathe Carolina - Blackout
- Bridgit Mendler - Ready Or Not
- Britney Spears & Iggy Azalea - Pretty Girls
- Britney Spears - Break The Ice
- Britney Spears - Circus
- Britney Spears - Criminal
- Britney Spears - Hold It Against Me
- Britney Spears - I Wanna Go
- Britney Spears - If U Seek Amy
- Britney Spears Featuring G-Eazy - Make Me...
- Britney Spears - Ooh La La
- Britney Spears - Perfume
- Britney Spears - Piece Of Me
- Britney Spears - Radar
- Britney Spears - Womanizer
- Britt Nicole - Gold
- BROCKHAMPTON - SUGAR
- Bronte Fall - Invited To The Party
- Bruno Mars - 24K Magic
- Bruno Mars - Gorilla
- Bruno Mars - Grenade
- Bruno Mars - I Just Might
- Bruno Mars - It Will Rain
- Bruno Mars - Just The Way You Are
- Bruno Mars - Locked Out Of Heaven
- Bruno Mars - Risk It All
- Bruno Mars - That's What I Like
- Bruno Mars - The Lazy Song
- Bruno Mars - Treasure
- Bruno Mars - Versace On The Floor
- Bruno Mars - When I Was Your Man
- Bruno Mars - Young Girls
- Bryce Vine - Baby Girl
- Bryce Vine - Drew Barrymore
- Bryce Vine Featuring YG - La La Land
- BTS - Butter
- BTS - Dynamite
- BTS - Fake Love
- BTS - Normal
- BTS - Swim
- Buckcherry - Sorry
- C-Side Featuring Keyshia Cole - Boyfriend/Girlfriend
- Calum Scott - Dancing On My Own
- Calvin Harris & Disciples - How Deep Is Your Love
- Calvin Harris & Ellie Goulding - Miracle
- Calvin Harris Featuring Rihanna - This Is What You Came For
- Calvin Harris Featuring Kehlani & Lil Yachty - Faking It
- Calvin Harris - Feel So Close
- Calvin Harris Featuring Ellie Goulding - I Need Your Love
- Calvin Harris - My Way
- Calvin Harris Featuring Haim - Pray To God
- Calvin Harris - Summer
- Calvin Harris Featuring Florence Welch - Sweet Nothing
- Calvin Harris Featuring Ayah Marar - Thinking About You
- Camila Cabello - Consequences
- Camila Cabello - Crying In The Club
- Camila Cabello - Don't Go Yet
- Camila Cabello - Liar
- Camila Cabello - Never Be The Same
- Camila Cabello - Shameless
- Capital Cities - Safe And Sound
- Carly Rae Jepsen - Call Me Maybe
- Carly Rae Jepsen - I Really Like You
- Carly Rae Jepsen - This Kiss
- Carly Rae Jepsen - Tonight I'm Getting Over You
- Cartel - The Perfect Mistake
- Cascada - Evacuate The Dancefloor
- Cascada - What Hurts The Most
- Cash Cash - Surrender
- Cash Cash Featuring Bebe Rexha - Take Me Home
- CeeLo Green - Bright Lights Bigger City
- Chance the Rapper Featuring Knox Fortune - All Night
- Chappell Roan - Good Luck, Babe!
- Chappell Roan - Hot To Go!
- Chappell Roan - Pink Pony Club
- Chappell Roan - The Giver
- Chappell Roan - The Subway
- Charli xcx - 360
- Charli xcx - Apple
- Charli xcx - Boom Clap
- Charli xcx - Break The Rules
- Charli xcx - Good Ones
- Charli xcx - Party 4 U
- Charli xcx - Speed Drive
- Charlie Puth - Attention
- Charlie Puth Featuring Kehlani - Done For Me
- Charlie Puth - How Long
- Charlie Puth - Light Switch
- Charlie Puth Featuring Meghan Trainor - Marvin Gaye
- Charlie Puth - Mother
- Charlie Puth - One Call Away
- Charlie Puth Featuring Dan + Shay - That's Not How This Works
- Charlie Puth - The Way I Am
- Charlie Puth Featuring Selena Gomez - We Don't Talk Anymore
- charlieonnafriday - Enough
- Charlotte Sands - Dress
- Cheat Codes & Little Mix - Only You
- Cheat Codes & Tinashe - Lean On Me
- Cheat Codes Featuring Fetty Wap & CVBZ - Feels Great
- Cheat Codes Featuring Demi Lovato - No Promises
- Chelsea Cutler - Sad Tonight
- Cher - DJ Play A Christmas Song
- Cher Lloyd Featuring Becky G - Oath
- Cher Lloyd - Want U Back
- Cher Lloyd - With Ur Love
- Cherish Featuring Yung Joc - Killa
- Childish Gambino - V. 3005
- Chris Brown & Tyga - Ayo
- Chris Brown & Young Thug - Go Crazy
- Chris Brown - Don't Wake Me Up
- Chris Brown - Fine China
- Chris Brown - Forever
- Chris Brown - Holy Blindfold
- Chris Brown Featuring Bryson Tiller - It Depends
- Chris Brown Featuring T-Pain - Kiss Kiss
- Chris Brown Featuring Lil Wayne & Busta Rhymes - Look At Me Now
- Chris Brown Featuring Nicki Minaj - Love More
- Chris Brown Featuring Usher & Rick Ross - New Flame
- Chris Brown - Residuals
- Chris Brown - She Ain't You
- Chris Brown - Summer Too Hot
- Chris Brown - Turn Up The Music
- Chris Brown - Under The Influence
- Chris Brown - With You
- Chris Brown - Yeah 3X
- Chris Brown - Zero
- Chris Rene - Young Homie
- Chris Wallace - Keep Me Crazy
- Chris Wallace - Remember When (Push Rewind)
- Christina Aguilera - Keeps Gettin' Better
- Christina Aguilera - Not Myself Tonight
- Christina Aguilera - Your Body
- Christina Perri - A Thousand Years
- Christina Perri - Human
- Christina Perri - Jar Of Hearts
- Ciara Featuring Justin Timberlake - Love Sex Magic
- CJ - Whoopty
- CKay - Love Nwantiti (Ah Ah Ah)
- Clean Bandit Featuring Julia Michaels - I Miss You
- Cobra Starship Featuring Leighton Meester - Good Girls Go Bad
- Cobra Starship - Hot Mess
- Cobra Starship Featuring Mac Miller - Middle Finger
- Cobra Starship Featuring Sabi - You Make Me Feel...
- Cody Simpson - On My Mind
- Cody Simpson - Pretty Brown Eyes
- Coi Leray - Players
- Colbie Caillat - Brighter Than The Sun
- Colbie Caillat - Bubbly
- Colbie Caillat - Fallin' For You
- Colbie Caillat - Realize
- Colby O'Donis Featuring Akon - What You Got
- Coldplay - A Sky Full Of Stars
- Coldplay - Adventure Of A Lifetime
- Coldplay Featuring Rihanna - Princess Of China
- Coldplay - Every Teardrop Is A Waterfall
- Coldplay - feelslikeimfallinginlove
- Coldplay - Higher Power
- Coldplay - Hymn For The Weekend
- Coldplay - Paradise
- Coldplay - Viva La Vida
- Conan Gray - Heather
- Conan Gray - Maniac
- Conan Gray - Never Ending Song
- Conan Gray - Overdrive
- Conan Gray - People Watching
- Conan Gray - Vodka Cranberry
- Conor Maynard Featuring Ne-Yo - Turn Around
- Conor Maynard - Vegas Girl
- Conrad Sewell - Hold Me Up
- Corbyn Besson & Tzuyu - Blink
- Creed - Rain
- Curtis Waters Featuring Harm Franklin - Stunnin
- Cyn - Drinks
- d4vd - Feel It
- Damiano David - Born With A Broken Heart
- Dan + Shay - Speechless
- Dan + Shay - Tequila
- Danity Kane - Damaged
- Dasha - Not At This Party
- Daughtry - Feels Like Tonight
- Daughtry - Life After You
- Daughtry - No Surprise
- Daughtry - Over You
- Daughtry - September
- Daughtry - Waiting For Superman
- Daughtry - What About Now
- David Archuleta - Crush
- David Banner Featuring Chris Brown - Get Like Me
- David Cook - Light On
- David Cook - The Time Of My Life
- David Guetta, Alphaville & Ava Max - Forever Young
- David Guetta & Chris Willis - Gettin' Over You
- David Guetta Featuring Rihanna - Who's That Chick?
- David Guetta, Anne-Marie & Coi Leray - Baby Don't Hurt Me
- David Guetta Featuring Anne-Marie - Don't Leave Me Alone
- David Guetta Featuring Chris Brown & Lil Wayne - I Can Only Imagine
- David Guetta & Chris Willis - Love Is Gone
- David Guetta Featuring Ne-Yo & Akon - Play Hard
- David Guetta Featuring Akon - Sexy Chick
- David Guetta Featuring Nicki Minaj - Turn Me On
- David Guetta Featuring Kelly Rowland - When Love Takes Over
- David Guetta Featuring Flo Rida & Nicki Minaj - Where Them Girls At
- David Guetta Featuring Usher - Without You
- David Kushner - Daylight
- Daya - Bad Girl
- Daya - Hide Away
- Daya - New
- Daya - Sit Still, Look Pretty
- Daya - Words
- Dean Lewis - Be Alright
- Delacey - My Man
- Demi Lovato - Confident
- Demi Lovato - Cool For The Summer
- Demi Lovato - Give Your Heart A Break
- Demi Lovato - Heart Attack
- Demi Lovato - I Love Me
- Demi Lovato - Made In The USA
- Demi Lovato Featuring Ariana Grande - Met Him Last Night
- Demi Lovato - Neon Lights
- Demi Lovato Featuring Cher Lloyd - Really Don't Care
- Demi Lovato - Skyscraper
- Demi Lovato - Sorry Not Sorry
- Demi Lovato - Stone Cold
- Demi Lovato - Tell Me You Love Me
- Dennis Lloyd - Nevermind
- Desiigner - Panda
- Dev Featuring The Cataracs - Bass Down Low
- Dev - In The Dark
- Dev & Enrique Iglesias - Naked
- Dexter And The Moonrocks - Freakin' Out
- Diddy - Dirty Money Featuring Skylar Grey - Coming Home
- Diddy - Dirty Money Featuring T.I. - Hello Good Morning
- Dillon Francis & Kygo Featuring James Hersey - Coming Over
- Diplo & Miguel - Don't Forget My Love
- Diplo & Sleepy Tom - Be Right There
- Diplo, Jessie Murph & Polo G - Heartbroken
- Disclosure Featuring Sam Smith - Latch
- Disclosure Featuring Sam Smith - Omen
- Disco Lines & Tinashe - No Broke Boys
- Dixie D'Amelio - Be Happy
- Dixie Featuring Rubi Rose - Psycho
- DJ Felli Fel Featuring Diddy, Akon, Ludacris & Lil Jon - Get Buck In Here
- DJ Khaled Featuring Drake - For Free
- DJ Khaled Featuring Post Malone, Megan Thee Stallion, Lil Baby & DaBaby - I Did It
- DJ Khaled Featuring Drake, Rick Ross & Lil Wayne - I'm On One
- DJ Khaled Featuring SZA - Just Us
- DJ Khaled Featuring Justin Bieber, Chance the Rapper & Quavo - No Brainer
- DJ Khaled Featuring Beyonce & JAY Z - Shining
- DJ Snake & AlunaGeorge - You Know You Like It
- DJ Snake & Lil Jon - Turn Down For What
- DJ Snake Featuring Justin Bieber - Let Me Love You
- DJ Snake Featuring Bipolar Sunshine - Middle
- Djo - End Of Beginning
- DNCE - Body Moves
- DNCE - Cake By The Ocean
- DNCE Featuring Nicki Minaj - Kissing Strangers
- DNCE - Toothbrush
- Doechii - Anxiety
- Doechii - Denial Is A River
- Doechii Featuring Kodak Black - What It Is (Block Boy)
- Doja Cat - Agora Hills
- Doja Cat - Attention
- Doja Cat - Get Into It (Yuh)
- Doja Cat - Gorgeous
- Doja Cat - Jealous Type
- Doja Cat - Need To Know
- Doja Cat - OKLOSER
- Doja Cat - Paint The Town Red
- Doja Cat - Say So
- Doja Cat - Vegas
- Doja Cat - Woman
- Dominic Fike - Babydoll
- Dominic Fike - Mona Lisa
- Don Toliver - E85
- Dove Cameron - Boyfriend
- Drake - Best I Ever Had
- Drake - Controlla
- Drake - Fake Love
- Drake - Find Your Love
- Drake - God's Plan
- Drake - Headlines
- Drake Featuring Majid Jordan - Hold On, We're Going Home
- Drake - Hotline Bling
- Drake - In My Feelings
- Drake Featuring Lil Durk - Laugh Now Cry Later
- Drake - Massive
- Drake - Nice For What
- Drake - Nokia
- Drake - Passionfruit
- Drake - Started From The Bottom
- Drake Featuring Lil Wayne - The Motto
- Drake - Toosie Slide
- Drake - What's Next
- Drop City Yacht Club Featuring Jeremih - Crickets
- Dua Lipa - Be The One
- Dua Lipa - Blow Your Mind (Mwah)
- Dua Lipa - Break My Heart
- Dua Lipa - Dance The Night
- Dua Lipa - Don't Start Now
- Dua Lipa - Houdini
- Dua Lipa - IDGAF
- Dua Lipa - Illusion
- Dua Lipa - Levitating
- Dua Lipa - Love Again
- Dua Lipa - New Rules
- Dua Lipa - Swan Song
- Dua Lipa - Training Season
- Dua Lipa - We're Good
- Duffy - Mercy
- Duke Dumont - Ocean Drive
- Duncan Laurence - Arcade
- Echosmith - Bright
- Echosmith - Cool Kids
- Echosmith - Over My Head
- Ed Sheeran - Afterglow
- Ed Sheeran & Elton John - Merry Christmas
- Ed Sheeran - Azizam
- Ed Sheeran - Bad Habits
- Ed Sheeran - Camera
- Ed Sheeran - Castle On The Hill
- Ed Sheeran - Don't
- Ed Sheeran - Eyes Closed
- Ed Sheeran - Lego House
- Ed Sheeran - Perfect
- Ed Sheeran - Photograph
- Ed Sheeran - Shape Of You
- Ed Sheeran - Shivers
- Ed Sheeran - Sing
- Ed Sheeran - The A Team
- Ed Sheeran Featuring Taylor Swift - The Joker And The Queen
- Ed Sheeran - Thinking Out Loud
- Eddie Benjamin - Weatherman
- Eden XO - Too Cool To Dance

## 2. Demucs와 motif scorer 준비

In [ ]:
import urllib.request
from mohim.motif import MotifConfig, MotifExtractor, create_beat_tracker, onset_variation
from mohim.dataset import DatasetBuilder
from mohim.separator import StemSeparator

BEAT_CHECKPOINT.parent.mkdir(parents=True, exist_ok=True)
if not BEAT_CHECKPOINT.is_file():
    urllib.request.urlretrieve(
        'https://cloud.cp.jku.at/public.php/dav/files/7ik4RrBKTS273gp/final0.ckpt', BEAT_CHECKPOINT
    )
separator = StemSeparator(
    device=DEVICE, model_name='htdemucs_6s', shifts=DEMUCS_SHIFTS
)
beat_tracker = create_beat_tracker(BEAT_CHECKPOINT, device=DEVICE)
motif_scorer = MotifExtractor(
    beat_tracker,
    MotifConfig(
        bars=MOTIF_BARS,
        search_seconds=MOTIF_SEARCH_SECONDS,
        min_presence=MIN_ACTIVE_RATIO,
        max_similarity_difference=MAX_ONSET_CHROMA_DIFFERENCE,
        onset_threshold=MIN_ONSET_SIMILARITY,
        pitch_class_span_threshold=MIN_PITCH_CLASS_SPAN,
        mean_centered_similarity_threshold=MIN_MEAN_CENTERED_SIMILARITY,
        onset_variation_threshold=MIN_ONSET_VARIATION,
    ),
)

dataset_builder = (
    DatasetBuilder(
        audio_dir=BILLBOARD_DATASET_DIR / 'audio',
        output_dir=MOTIF_DATASET_DIR,
        separator=separator,
        motif_extractor=motif_scorer,
        audio_format=AUDIO_FORMAT,
        resume=not FORCE_REPROCESS,
    )
    if DATA_SOURCE == 'billboard' else None
)
print('separator and motif scorer ready')

separator and motif scorer ready

## 3. 모든 stem × start-downbeat 후보 계산

`DEMUCS_BATCH_SIZE`개 곡을 한 GPU batch로 분리하고, 해당 batch의 곡 × stem 점수 계산은 `MOTIF_WORKERS`개 CPU thread로 병렬 실행합니다. Raw onset/chroma는 1차 후보 필터에 사용하고, mean-centered onset/chroma는 stem별 최초 후보의 최종 순위와 0.28 하한 검사에 사용합니다. Onset 하한에 미달한 후보는 pitch-class span 계산을 생략하며, `candidate_*.flac`은 active ratio, raw onset/chroma 차이, raw onset, pitch-class span 조건까지 통과한 구간만 저장합니다.

In [ ]:
from collections import Counter
import json
import librosa
import numpy as np
import pandas as pd
import re
import shutil
from mohim.separator import save_audio

def average_next_bar_score_gain(current, next_candidate):
    """
    현재 후보보다 다음 마디 후보의 4개 점수가
    평균적으로 얼마나 좋아졌는지 계산.
    """
    gains = [
        next_candidate[key] - current[key]
        for key in BAR_ALIGNMENT_SCORE_KEYS
    ]

    return float(np.mean(gains))

def safe_folder_name(value):
    cleaned = re.sub(r'[\\/:*?"<>|\x00-\x1f]', '_', value)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip(' .')
    return cleaned[:120] or 'untitled'

def song_display_title(song):
    return f"{song['artist']} - {song['title']}" if song['artist'] else song['title']

diagnostic_base_name_counts = Counter(
    safe_folder_name(song_display_title(song)) for song in songs
)

def diagnostic_song_id(song):
    base_name = safe_folder_name(song_display_title(song))
    if diagnostic_base_name_counts[base_name] == 1:
        return base_name
    short_track_id = safe_folder_name(str(song['track_id']))[:8]
    return f'{base_name[:109]} [{short_track_id}]'

def song_stem_metadata_path(song):
    display_title = song_display_title(song)
    return SONGS_STEM_DIR / safe_folder_name(display_title) / 'metadata.json'

def song_stems_complete(song, audio_path):
    metadata_path = song_stem_metadata_path(song)
    if not metadata_path.is_file():
        return False
    try:
        metadata = json.loads(metadata_path.read_text(encoding='utf-8'))
        same_audio = Path(metadata.get('source_audio', '')).resolve() == Path(audio_path).resolve()
        stem_files = metadata.get('stem_files')
        return (
            same_audio
            and isinstance(stem_files, dict)
            and stem_files
            and all((metadata_path.parent / filename).is_file() for filename in stem_files.values())
        )
    except (OSError, ValueError, TypeError):
        return False

def save_song_stems(song, audio_path, stems, sample_rate):
    metadata_path = song_stem_metadata_path(song)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    stem_files = {}
    for stem_name, stem_audio in stems.items():
        if not stem_name.replace('_', '').isalnum():
            raise ValueError(f'Unsafe separator stem name: {stem_name!r}')
        filename = f'{stem_name}.{AUDIO_FORMAT}'
        save_audio(metadata_path.parent / filename, stem_audio, sample_rate, audio_format=AUDIO_FORMAT)
        stem_files[stem_name] = filename
    metadata = {
        'track_id': song['track_id'], 'artist': song['artist'], 'title': song['title'],
        'source_audio': str(audio_path), 'sample_rate': sample_rate, 'stem_files': stem_files,
    }
    metadata_path.write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2), encoding='utf-8'
    )
    return metadata_path.parent

def internal_candidate_features(audio_path):
    audio, sample_rate = librosa.load(audio_path, sr=None, mono=True)
    hop_length = 512
    chroma = librosa.feature.chroma_cens(
        y=audio, sr=sample_rate, hop_length=hop_length
    )
    chroma_sum = chroma.sum(axis=0, keepdims=True)
    valid_chroma = chroma_sum.ravel() > 1e-8
    chroma_norm = np.divide(
        chroma, chroma_sum, out=np.zeros_like(chroma), where=chroma_sum > 1e-8
    )
    valid_pairs = valid_chroma[:-1] & valid_chroma[1:]
    if np.any(valid_pairs):
        frame_flux = 0.5 * np.sum(np.abs(np.diff(chroma_norm, axis=1)), axis=0)
        chroma_flux = float(np.mean(frame_flux[valid_pairs]))
    else:
        chroma_flux = 0.0
    return {'chroma_flux': chroma_flux}

def candidate_passes_export_filters(row):
    return (
        row['active_ratio'] >= MIN_ACTIVE_RATIO
        and abs(row['onset_similarity'] - row['chroma_similarity']) <= MAX_ONSET_CHROMA_DIFFERENCE
        and row['onset_similarity'] >= MIN_ONSET_SIMILARITY
        and row['pitch_class_span'] is not None
        and row['pitch_class_span'] >= MIN_PITCH_CLASS_SPAN
    )

motif_result_counts = {'successed': 0, 'failed': 0}

def print_motif_result(title, succeeded, detail=None):
    result_key = 'successed' if succeeded else 'failed'
    motif_result_counts[result_key] += 1
    label = 'selection' if succeeded else 'skipped'
    counts = (
        f"successed: {motif_result_counts['successed']} / "
        f"failed: {motif_result_counts['failed']}"
    )
    detail_suffix = f' - {detail}' if detail else ''
    print(f'  [{label}] {title} ({counts}){detail_suffix}')

MIN_NEXT_BAR_SCORE_GAIN = 0.05

BAR_ALIGNMENT_SCORE_KEYS = (
    'onset_similarity',
    'chroma_similarity',
    'mean_centered_onset_similarity',
    'mean_centered_chroma_similarity',
)


def average_next_bar_score_gain(current, next_candidate):
    """
    현재 후보와 다음 마디 후보의 4개 점수 차이(next - current)를
    평균내서 다음 마디로 이동할지 판단.
    """
    return float(np.mean([
        next_candidate[key] - current[key]
        for key in BAR_ALIGNMENT_SCORE_KEYS
    ]))


def save_earliest_valid_selection(metadata_path, metadata):
    # 이전 selection 파일 제거
    for stale_name in (
        'motif_selections.json',
        'selected_earliest.flac',
        'selected_highest_similarity.flac',
    ):
        stale_path = metadata_path.parent / stale_name
        if stale_path.is_file():
            stale_path.unlink()

    # =========================================================
    # 1. 1차 유효성 필터
    #
    # 여기서는:
    #   - active_ratio
    #   - onset_similarity
    #   - onset/chroma difference
    #   - pitch_class_span
    #
    # 만 검사.
    #
    # mean-centered / onset_variation은 아직 검사하지 않음.
    # =========================================================
    eligible = [
        row
        for row in metadata['candidates']
        if candidate_passes_export_filters(row)
    ]

    if not eligible:
        skipped_metadata = {
            'song_id': metadata['song_id'],
            'title': metadata['title'],
            'source_audio': metadata['source_audio'],
            'status': 'skipped',
            'reason': 'no_candidate_passed_export_filters',

            'min_active_ratio': MIN_ACTIVE_RATIO,
            'max_onset_chroma_difference': MAX_ONSET_CHROMA_DIFFERENCE,
            'onset_threshold': MIN_ONSET_SIMILARITY,
            'pitch_class_span_threshold': MIN_PITCH_CLASS_SPAN,
            'mean_centered_similarity_threshold': MIN_MEAN_CENTERED_SIMILARITY,
            'onset_variation_threshold': MIN_ONSET_VARIATION,
            'next_bar_score_gain_threshold': MIN_NEXT_BAR_SCORE_GAIN,

            'similarity_mode': SIMILARITY_MODE,
            'candidate_count': len(metadata['candidates']),
            'eligible_candidate_count': 0,

            'alignment_decisions': {},
            'selected_by_stem_before_final_check': {},
            'final_validation': {},
            'selections': {},
        }

        (metadata_path.parent / 'motif_selections.json').write_text(
            json.dumps(
                skipped_metadata,
                ensure_ascii=False,
                indent=2,
            ),
            encoding='utf-8',
        )

        print_motif_result(
            metadata['title'],
            False,
            '1차 조건 통과 후보 없음',
        )

        return skipped_metadata

    # =========================================================
    # 2. stem별로 1차 유효 후보 묶기
    # =========================================================
    candidates_by_stem = {}

    for row in eligible:
        candidates_by_stem.setdefault(
            row['stem_name'],
            [],
        ).append(row)

    # 각 stem 내부는 시간순 정렬
    for stem_name in candidates_by_stem:
        candidates_by_stem[stem_name].sort(
            key=lambda row: row['start_sec']
        )

    # =========================================================
    # 3. stem 내부 시작점 결정
    #
    # 가장 이른 1차 유효 후보부터 시작.
    #
    # current → next의 4개 점수 평균 개선량이
    # 0.05 이상이면 다음 마디로 이동.
    #
    # 이 단계에서는 최종 threshold를 검사하지 않음.
    # =========================================================
    selected_by_stem_before_final_check = {}
    alignment_decisions = {}

    for stem_name, stem_rows in candidates_by_stem.items():
        current_pos = 0
        current = stem_rows[current_pos]

        decisions = []

        while current_pos + 1 < len(stem_rows):
            next_pos = current_pos + 1
            next_candidate = stem_rows[next_pos]

            score_differences = {
                key: float(
                    next_candidate[key] - current[key]
                )
                for key in BAR_ALIGNMENT_SCORE_KEYS
            }

            average_gain = float(np.mean(
                list(score_differences.values())
            ))

            decision = {
                'current_candidate_index': current['candidate_index'],
                'current_start_sec': current['start_sec'],

                'next_candidate_index': next_candidate['candidate_index'],
                'next_start_sec': next_candidate['start_sec'],

                'score_differences': score_differences,
                'average_score_gain': average_gain,
                'threshold': MIN_NEXT_BAR_SCORE_GAIN,
            }

            # ---------------------------------------------
            # 다음 마디가 평균적으로 0.05 이상 더 좋으면 이동
            # ---------------------------------------------
            if average_gain >= MIN_NEXT_BAR_SCORE_GAIN:
                decision['action'] = 'move_to_next_bar'
                decisions.append(decision)

                current_pos = next_pos
                current = next_candidate

                # 이동했으므로 새 current와 그 다음 후보를 다시 비교
                continue

            # ---------------------------------------------
            # 충분한 차이가 아니면 현재 시작점 유지
            # ---------------------------------------------
            decision['action'] = 'keep_current'
            decisions.append(decision)

            break

        selected_by_stem_before_final_check[stem_name] = dict(current)

        alignment_decisions[stem_name] = {
            'initial_candidate_index': stem_rows[0]['candidate_index'],
            'initial_start_sec': stem_rows[0]['start_sec'],

            'selected_candidate_index': current['candidate_index'],
            'selected_start_sec': current['start_sec'],

            'decisions': decisions,
        }

    # =========================================================
    # 4. 이제 stem별로 선택된 후보에 대해서만 최종 점검
    #
    #   - mean-centered onset similarity
    #   - mean-centered chroma similarity
    #   - onset variation
    #
    # 여기서 실패하면 그 stem은 최종 후보에서 탈락.
    # 다른 candidate로 fallback하지 않음.
    # =========================================================
    final_valid_by_stem = {}
    final_validation = {}

    for stem_name, selected_row in (
        selected_by_stem_before_final_check.items()
    ):
        row = dict(selected_row)

        validation = {
            'candidate_index': row['candidate_index'],
            'start_sec': row['start_sec'],

            'mean_centered_onset_similarity':
                row['mean_centered_onset_similarity'],

            'mean_centered_chroma_similarity':
                row['mean_centered_chroma_similarity'],
        }

        # ---------------------------------------------
        # 4-1. mean-centered similarity 최종 검사
        # ---------------------------------------------
        mean_centered_onset_pass = (
            row['mean_centered_onset_similarity']
            >= MIN_MEAN_CENTERED_SIMILARITY
        )

        mean_centered_chroma_pass = (
            row['mean_centered_chroma_similarity']
            >= MIN_MEAN_CENTERED_SIMILARITY
        )

        validation['mean_centered_onset_pass'] = (
            mean_centered_onset_pass
        )

        validation['mean_centered_chroma_pass'] = (
            mean_centered_chroma_pass
        )

        if not (
            mean_centered_onset_pass
            and mean_centered_chroma_pass
        ):
            validation['passed'] = False
            validation['reason'] = (
                'mean_centered_similarity_below_threshold'
            )

            final_validation[stem_name] = validation
            continue

        # ---------------------------------------------
        # 4-2. onset variation 최종 검사
        # ---------------------------------------------
        candidate_path = (
            metadata_path.parent
            / row['candidate_file']
        )

        candidate_audio, candidate_sample_rate = librosa.load(
            candidate_path,
            sr=None,
            mono=False,
        )

        variation = onset_variation(
            candidate_audio,
            candidate_sample_rate,
        )

        row['onset_variation'] = variation

        validation['onset_variation'] = variation
        validation['onset_variation_pass'] = (
            variation >= MIN_ONSET_VARIATION
        )

        if variation < MIN_ONSET_VARIATION:
            validation['passed'] = False
            validation['reason'] = (
                'onset_variation_below_threshold'
            )

            final_validation[stem_name] = validation
            continue

        # ---------------------------------------------
        # 최종 통과
        # ---------------------------------------------
        validation['passed'] = True
        validation['reason'] = None

        final_validation[stem_name] = validation
        final_valid_by_stem[stem_name] = row

    # =========================================================
    # 5. 모든 stem이 최종 검사에서 탈락한 경우
    # =========================================================
    if not final_valid_by_stem:
        skipped_metadata = {
            'song_id': metadata['song_id'],
            'title': metadata['title'],
            'source_audio': metadata['source_audio'],
            'status': 'skipped',
            'reason': 'no_stem_candidate_passed_final_validation',

            'min_active_ratio': MIN_ACTIVE_RATIO,
            'max_onset_chroma_difference': MAX_ONSET_CHROMA_DIFFERENCE,
            'onset_threshold': MIN_ONSET_SIMILARITY,
            'pitch_class_span_threshold': MIN_PITCH_CLASS_SPAN,
            'mean_centered_similarity_threshold':
                MIN_MEAN_CENTERED_SIMILARITY,
            'onset_variation_threshold': MIN_ONSET_VARIATION,
            'next_bar_score_gain_threshold': MIN_NEXT_BAR_SCORE_GAIN,

            'bar_alignment_score_keys':
                list(BAR_ALIGNMENT_SCORE_KEYS),

            'similarity_mode': SIMILARITY_MODE,

            'candidate_count': len(metadata['candidates']),
            'eligible_candidate_count': len(eligible),

            'alignment_decisions': alignment_decisions,
            'selected_by_stem_before_final_check':
                selected_by_stem_before_final_check,
            'final_validation': final_validation,

            'selections': {},
        }

        (metadata_path.parent / 'motif_selections.json').write_text(
            json.dumps(
                skipped_metadata,
                ensure_ascii=False,
                indent=2,
            ),
            encoding='utf-8',
        )

        print_motif_result(
            metadata['title'],
            False,
            'stem별 시작점 결정 후 최종 검증 통과 후보 없음',
        )

        return skipped_metadata

    # =========================================================
    # 6. 최종 검증까지 통과한 stem 후보들 중
    #    가장 이른 start_sec 선택
    # =========================================================
    earliest = dict(
        min(
            final_valid_by_stem.values(),
            key=lambda row: row['start_sec'],
        )
    )

    selection_file = 'selected_earliest.flac'

    shutil.copy2(
        metadata_path.parent / earliest['candidate_file'],
        metadata_path.parent / selection_file,
    )

    earliest['selection_file'] = selection_file

    # =========================================================
    # 7. selection metadata 저장
    # =========================================================
    selection_metadata = {
        'song_id': metadata['song_id'],
        'title': metadata['title'],
        'source_audio': metadata['source_audio'],
        'status': 'selected',

        'min_active_ratio': MIN_ACTIVE_RATIO,
        'max_onset_chroma_difference': MAX_ONSET_CHROMA_DIFFERENCE,
        'onset_threshold': MIN_ONSET_SIMILARITY,
        'pitch_class_span_threshold': MIN_PITCH_CLASS_SPAN,
        'mean_centered_similarity_threshold':
            MIN_MEAN_CENTERED_SIMILARITY,
        'onset_variation_threshold': MIN_ONSET_VARIATION,

        'next_bar_score_gain_threshold': MIN_NEXT_BAR_SCORE_GAIN,
        'bar_alignment_score_keys': list(BAR_ALIGNMENT_SCORE_KEYS),

        'similarity_mode': SIMILARITY_MODE,

        'candidate_count': len(metadata['candidates']),
        'eligible_candidate_count': len(eligible),

        # 시작점 보정 과정
        'alignment_decisions': alignment_decisions,

        # 최종 검증 전 stem별 선택 결과
        'selected_by_stem_before_final_check':
            selected_by_stem_before_final_check,

        # 최종 검증 결과
        'final_validation': final_validation,

        # 최종 검증까지 통과한 stem들
        'final_valid_by_stem': final_valid_by_stem,

        # 곡 전체 최종 선택
        'selections': {
            'earliest': earliest,
        },
    }

    (metadata_path.parent / 'motif_selections.json').write_text(
        json.dumps(
            selection_metadata,
            ensure_ascii=False,
            indent=2,
        ),
        encoding='utf-8',
    )

    print_motif_result(
        metadata['title'],
        True,
        (
            f"{earliest['stem_name']} "
            f"@ {earliest['start_sec']:.2f}s"
        ),
    )

    return selection_metadata

all_rows = []
dataset_results = []
audio_failures = []
pending_jobs = []

def is_audio_decode_error(error):
    decode_markers = ('Failed to decode audio samples', 'Could not push packet', 'Invalid data found')
    seen = set()
    while error is not None and id(error) not in seen:
        if any(marker in str(error) for marker in decode_markers):
            return True
        seen.add(id(error))
        error = error.__cause__ or error.__context__
    return False

assert DEMUCS_BATCH_SIZE >= 1
assert MOTIF_WORKERS >= 1
for song_index, audio_path in enumerate(song_paths):
    song = songs[song_index]
    display_title = song_display_title(song)
    print(f'[{song_index + 1}/{len(song_paths)}] {display_title}')
    song_id = diagnostic_song_id(song)
    song_dir = DIAGNOSTIC_DIR / song_id
    if not FORCE_REPROCESS and not song_dir.exists():
        legacy_song_dir = DIAGNOSTIC_DIR / f'{song_index:03d}_{safe_folder_name(display_title)}'
        if legacy_song_dir.exists():
            legacy_song_dir.rename(song_dir)
            print(f'  [rename] {legacy_song_dir.name} -> {song_dir.name}')
    metadata_path = song_dir / 'motif_scores.json'

    existing = None
    if not FORCE_REPROCESS and metadata_path.is_file() and (song_dir / 'melodic_accompaniment.flac').is_file():
        try:
            candidate_metadata = json.loads(metadata_path.read_text(encoding='utf-8'))
            same_audio = (
                Path(candidate_metadata.get('source_audio', '')).resolve()
                == Path(audio_path).resolve()
            )
            same_similarity_mode = candidate_metadata.get('similarity_mode') == SIMILARITY_MODE
            candidates = candidate_metadata.get('candidates')
            candidates_complete = isinstance(candidates, list) and all(
                'pitch_class_span' in row
                and 'mean_centered_onset_similarity' in row
                and 'mean_centered_chroma_similarity' in row
                and (
                    not candidate_passes_export_filters(row)
                    or (
                        row.get('candidate_file')
                        and (song_dir / row['candidate_file']).is_file()
                    )
                )
                for row in candidate_metadata.get('candidates', [])
            )
            if same_audio and same_similarity_mode and candidates_complete:
                existing = candidate_metadata
        except (OSError, ValueError, TypeError):
            existing = None

    if existing is not None:
        selection_path = song_dir / 'motif_selections.json'
        try:
            cached_selection = json.loads(selection_path.read_text(encoding='utf-8'))
        except (OSError, ValueError, TypeError):
            cached_selection = None
        if cached_selection is not None and cached_selection.get('status') == 'skipped':
            same_skip_audio = (
                Path(cached_selection.get('source_audio', '')).resolve()
                == Path(audio_path).resolve()
            )
            same_skip_config = all((
                cached_selection.get('min_active_ratio') == MIN_ACTIVE_RATIO,
                cached_selection.get('max_onset_chroma_difference') == MAX_ONSET_CHROMA_DIFFERENCE,
                cached_selection.get('onset_threshold') == MIN_ONSET_SIMILARITY,
                cached_selection.get('pitch_class_span_threshold') == MIN_PITCH_CLASS_SPAN,
                cached_selection.get('mean_centered_similarity_threshold') == MIN_MEAN_CENTERED_SIMILARITY,
                cached_selection.get('onset_variation_threshold') == MIN_ONSET_VARIATION,
                cached_selection.get('similarity_mode') == SIMILARITY_MODE,
            ))
            if same_skip_audio and same_skip_config:
                for row in existing['candidates']:
                    all_rows.append({'song_id': song_id, 'title': display_title, **row})
                if dataset_builder is not None:
                    dataset_results.append(dataset_builder.record_rejection(
                        song['track'], cached_selection.get('reason', 'final_motif_rejected')
                    ))
                print_motif_result(
                    display_title, False, 'cached: 이전 실행에서 통과한 모티프 없음'
                )
                continue
            print('  [reprocess] 스킵 이후 음원 또는 임계값 변경')
            existing = None

    if existing is not None:
        selection_metadata = save_earliest_valid_selection(metadata_path, existing)
        if dataset_builder is not None:
            if selection_metadata['status'] == 'selected':
                selected_candidate = selection_metadata['selections']['earliest']
                validated_variation = selected_candidate['onset_variation']
                dataset_result = dataset_builder.process_track(
                    song['track'], audio_index,
                    validated_onset_variation=validated_variation,
                    selected_candidate=selected_candidate,
                )
            else:
                dataset_result = dataset_builder.record_rejection(
                    song['track'], selection_metadata.get('reason', 'final_motif_rejected')
                )
            dataset_results.append(dataset_result)
        elif not song_stems_complete(song, audio_path):
            print('  [process] 저장되지 않은 songs stem 분리')
            stems, sample_rate, mixture = separator.separate(audio_path)
            save_song_stems(song, audio_path, stems, sample_rate)
            del stems, mixture
        print('  [reuse] 기존 분리/후보 결과 사용')
        for row in existing['candidates']:
            all_rows.append({'song_id': song_id, 'title': display_title, **row})
        continue

    pending_jobs.append({
        'song_index': song_index, 'song': song, 'audio_path': audio_path,
        'display_title': display_title, 'song_id': song_id,
        'song_dir': song_dir, 'metadata_path': metadata_path,
    })

for batch_start in range(0, len(pending_jobs), DEMUCS_BATCH_SIZE):
    batch_jobs = pending_jobs[batch_start:batch_start + DEMUCS_BATCH_SIZE]
    batch_paths = [job['audio_path'] for job in batch_jobs]
    batch_number = batch_start // DEMUCS_BATCH_SIZE + 1
    batch_count = (len(pending_jobs) + DEMUCS_BATCH_SIZE - 1) // DEMUCS_BATCH_SIZE
    print(f'[Demucs batch {batch_number}/{batch_count}] {len(batch_jobs)}곡 분리')
    try:
        batch_separations = separator.separate_many(batch_paths)
    except RuntimeError as batch_error:
        if not is_audio_decode_error(batch_error):
            raise

        valid_jobs = []
        for job in batch_jobs:
            try:
                separator._load_audio(job['audio_path'])
            except Exception as audio_error:
                if not is_audio_decode_error(audio_error):
                    raise
                failure = {
                    'song_id': job['song_id'],
                    'title': job['display_title'],
                    'source_audio': str(job['audio_path']),
                    'status': 'failed',
                    'stage': 'audio_decode',
                    'error_type': type(audio_error).__name__,
                    'error_message': str(audio_error),
                }
                audio_failures.append(failure)
                print(f"  [skip: audio decode failed] {job['display_title']}: {audio_error}")
                if dataset_builder is not None:
                    dataset_results.append(dataset_builder.record_rejection(
                        job['song']['track'],
                        f"audio_decode_failed: {type(audio_error).__name__}: {audio_error}",
                    ))
            else:
                valid_jobs.append(job)

        batch_jobs = valid_jobs
        batch_paths = [job['audio_path'] for job in batch_jobs]
        batch_separations = separator.separate_many(batch_paths) if batch_paths else []
    assert len(batch_separations) == len(batch_jobs)
    batch_scores = motif_scorer.score_many(
        [
            (job['audio_path'], separation_result[0], separation_result[1])
            for job, separation_result in zip(batch_jobs, batch_separations)
        ],
        max_workers=MOTIF_WORKERS,
    )

    for job, separation_result, result in zip(batch_jobs, batch_separations, batch_scores):
        song = job['song']
        audio_path = job['audio_path']
        display_title = job['display_title']
        song_id = job['song_id']
        song_dir = job['song_dir']
        metadata_path = job['metadata_path']
        song_dir.mkdir(parents=True, exist_ok=True)
        stems, sample_rate, mixture = separation_result
        print(f'  [motif] {display_title}')
        if dataset_builder is None:
            save_song_stems(song, audio_path, stems, sample_rate)
        melodic = result['melodic_accompaniment']
        save_audio(song_dir / 'melodic_accompaniment.flac', melodic, sample_rate, audio_format='flac')

        for stale_candidate in song_dir.glob('candidate_*.flac'):
            stale_candidate.unlink()
        exported_candidates = [
            row for row in result['candidates'] if candidate_passes_export_filters(row)
        ]
        for row_index, row in enumerate(exported_candidates):
            start = round(row['start_sec'] * sample_rate)
            end = round(row['end_sec'] * sample_rate)
            filename = f"candidate_{row_index:03d}_{row['stem_name']}.flac"
            save_audio(song_dir / filename, melodic[:, start:end], sample_rate, audio_format='flac')
            row['candidate_file'] = filename
        for row in result['candidates']:
            all_rows.append({'song_id': song_id, 'title': display_title, **row})

        metadata = {
            'song_id': song_id, 'title': display_title, 'source_audio': str(audio_path),
            'sample_rate': sample_rate, 'similarity_mode': SIMILARITY_MODE,
            'candidates': result['candidates'],
        }
        metadata_path.write_text(
            json.dumps(metadata, ensure_ascii=False, indent=2), encoding='utf-8'
        )
        selection_metadata = save_earliest_valid_selection(metadata_path, metadata)
        if dataset_builder is not None:
            if selection_metadata['status'] == 'selected':
                selected_candidate = selection_metadata['selections']['earliest']
                validated_variation = selected_candidate['onset_variation']
                dataset_result = dataset_builder.process_track(
                    song['track'],
                    audio_index,
                    separation_result=separation_result,
                    motif_scores=result,
                    validated_onset_variation=validated_variation,
                    selected_candidate=selected_candidate,
                )
            else:
                dataset_result = dataset_builder.record_rejection(
                    song['track'], selection_metadata.get('reason', 'final_motif_rejected')
                )
            dataset_results.append(dataset_result)
        del stems, mixture, result, melodic

failure_report_path = DIAGNOSTIC_DIR / 'audio_failures.jsonl'
failure_report_path.write_text(
    ''.join(json.dumps(failure, ensure_ascii=False) + '\n' for failure in audio_failures),
    encoding='utf-8',
)
if audio_failures:
    print(f'[audio failures] {len(audio_failures)}곡: {failure_report_path}')

scores_df = pd.DataFrame(all_rows)
scores_df.to_csv(DIAGNOSTIC_DIR / 'all_motif_scores.csv', index=False)
if scores_df.empty:
    display(scores_df)
else:
    display(scores_df.sort_values(['song_id', 'start_sec', 'stem_name']))
if dataset_results:
    from dataclasses import asdict
    display(pd.DataFrame([asdict(result) for result in dataset_results]))

accepted_track_ids = sorted({
    result.track_id
    for result in dataset_results
    if result.status in {'accepted', 'skipped'} and result.output_dir is not None
})
motif_version = {
    'schema': 'mohim_motif_dataset_v5',
    'data_source': DATA_SOURCE,
    'max_songs': MAX_SONGS,
    'separator_model': 'htdemucs_6s',
    'demucs_shifts': DEMUCS_SHIFTS,
    'bars': MOTIF_BARS,
    'search_seconds': MOTIF_SEARCH_SECONDS,
    'min_active_ratio': MIN_ACTIVE_RATIO,
    'max_onset_chroma_difference': MAX_ONSET_CHROMA_DIFFERENCE,
    'min_onset_similarity': MIN_ONSET_SIMILARITY,
    'min_pitch_class_span': MIN_PITCH_CLASS_SPAN,
    'min_mean_centered_similarity': MIN_MEAN_CENTERED_SIMILARITY,
    'min_onset_variation': MIN_ONSET_VARIATION,
    'similarity_mode': SIMILARITY_MODE,
    'accepted_track_ids': accepted_track_ids,
}
MOTIF_VERSION_PATH.write_text(
    json.dumps(motif_version, ensure_ascii=False, sort_keys=True, indent=2) + '\n',
    encoding='utf-8',
)
print('motif dataset version:', MOTIF_VERSION_PATH)

Streaming output truncated to the last 5000 lines.
[1647/2129] Rihanna - Love On The Brain
[1648/2129] Rihanna - Needed Me
[1649/2129] Rihanna - Only Girl (In The World)
[1650/2129] Rihanna - Rehab
[1651/2129] Rihanna - Rude Boy
[1652/2129] Rihanna - Russian Roulette
[1653/2129] Rihanna - Take A Bow
[1654/2129] Rihanna Featuring Jay-Z - Talk That Talk
[1655/2129] Rihanna - What Now
[1656/2129] Rihanna Featuring Drake - What's My Name?
[1657/2129] Rihanna - Where Have You Been
[1658/2129] Rihanna - You Da One
[1659/2129] Rita Ora - How We Do (Party)
[1660/2129] Rita Ora - I Will Never Let You Down
[1661/2129] Rita Ora - Let You Love Me
[1662/2129] Rita Ora Featuring Fatboy Slim - Praising You
[1663/2129] Ritt Momney - Put Your Records On
[1664/2129] Rixton - Me And My Broken Heart
[1665/2129] Rixton - Wait On Me
[1666/2129] Rob Thomas - Her Diamonds
[1667/2129] Rob Thomas - Someday
[1668/2129] Robin Schulz Featuring Francesco Yates - Sugar
[1669/2129] Robin Thicke Featuring Nicki Minaj - Back Together
[1670/2129] Robin Thicke Featuring T.I. + Pharrell - Blurred Lines
[1671/2129] Robin Thicke - Feel Good
[1672/2129] Robin Thicke Featuring Kendrick Lamar - Give It 2 U
[1673/2129] Roddy Ricch - The Box
[1674/2129] Role Model - Sally, When The Wine Runs Out
[1675/2129] Rosa Linn - Snap
[1676/2129] Rudimental Featuring Ed Sheeran - Lay It All On Me
[1677/2129] Runner Runner - So Obvious
[1678/2129] Russell Dickerson - Happen To Me
[1679/2129] Ruth B - Lost Boy
[1680/2129] Ryn Weaver - OctaHate
[1681/2129] Sabrina Carpenter - Almost Love
[1682/2129] Sabrina Carpenter - Bed Chem
[1683/2129] Sabrina Carpenter - Busy Woman
[1684/2129] Sabrina Carpenter - Espresso
[1685/2129] Sabrina Carpenter - Feather
[1686/2129] Sabrina Carpenter - House Tour
[1687/2129] Sabrina Carpenter - Manchild
[1688/2129] Sabrina Carpenter - Nonsense
[1689/2129] Sabrina Carpenter - Please Please Please
[1690/2129] Sabrina Carpenter - Skin
[1691/2129] Sabrina Carpenter - Sue Me
[1692/2129] Sabrina Carpenter - Taste
[1693/2129] Sabrina Carpenter - Tears
[1694/2129] Sabrina Carpenter - Thumbs
[1695/2129] Sabrina Carpenter - When Did You Get Hot?
[1696/2129] Sabrina Carpenter - Why
[1697/2129] Sage The Gemini Featuring Nick Jonas - Good Thing
[1698/2129] Saint Jhn - Roses
[1699/2129] Salem Ilese - Mad At Disney
[1700/2129] Sam Feldt Featuring RANI - Post Malone
[1701/2129] Sam Hunt - Body Like A Back Road
[1702/2129] Sam Hunt - Take Your Time
[1703/2129] Sam Smith - Diamonds
[1704/2129] Sam Smith - How Do You Sleep?
[1705/2129] Sam Smith - I'm Not Here To Make Friends
[1706/2129] Sam Smith - I'm Not The Only One
[1707/2129] Sam Smith - Lay Me Down
[1708/2129] Sam Smith - Like I Can
[1709/2129] Sam Smith - Love Me More
[1710/2129] Sam Smith - Stay With Me
[1711/2129] Sam Smith - To Die For
[1712/2129] Sam Smith - Too Good At Goodbyes
[1713/2129] Sammy Adams - Only One
[1714/2129] Santana Featuring Chad Kroeger - Into The Night
[1715/2129] Sara Bareilles - Bottle It Up
[1716/2129] Sara Bareilles - Brave
[1717/2129] Sara Bareilles - King Of Anything
[1718/2129] Sara Bareilles - Love Song
[1719/2129] Sarah Reeves - Cloud Nine
[1720/2129] Savage Featuring Soulja Boy Tell'em - Swing
[1721/2129] Saving Abel - 18 Days
[1722/2129] Saving Jane - SuperGirl
[1723/2129] Saweetie Featuring H.E.R. - Closer
[1724/2129] Saweetie - My Type
[1725/2129] Saweetie - Tap In
[1726/2129] Sean Kingston & Justin Bieber - Eenie Meenie
[1727/2129] Sean Kingston Featuring T.I. - Back 2 Life (Live It Up)
[1728/2129] Sean Kingston Featuring Chris Brown & Wiz Khalifa - Beat It
[1729/2129] Sean Kingston - Face Drop
[1730/2129] Sean Kingston - Fire Burning
[1731/2129] Sean Kingston Featuring Nicki Minaj - Letting Go (Dutty Love)
[1732/2129] Sean Kingston - Take You There
[1733/2129] Sean Paul - She Doesn't Mind
[1734/2129] Sean Paul - So Fine
[1735/2129] Secondhand Serenade - Fall For You
[1736/2129] Seether - Careless Whisper
[1737/2129] Seether - Rise Above This
[1738/2129] Selena Gomez, Benny Blanco & Gracie Abrams - Call Me When You Break Up
[1739/2129] Selena Gomez & The Scene - Love You Like A Love Song
[1740/2129] Selena Gomez & The Scene - Naturally
[1741/2129] Selena Gomez & The Scene - Round & Round
[1742/2129] Selena Gomez & The Scene - Who Says
[1743/2129] Selena Gomez - Back To You
[1744/2129] Selena Gomez - Bad Liar
[1745/2129] Selena Gomez - Come & Get It
[1746/2129] Selena Gomez Featuring A$AP Rocky - Good For You
[1747/2129] Selena Gomez - Hands To Myself
[1748/2129] Selena Gomez - Kill Em With Kindness
[1749/2129] Selena Gomez - Lose You To Love Me
[1750/2129] Selena Gomez - Love On
[1751/2129] Selena Gomez - My Mind & Me
[1752/2129] Selena Gomez - Rare
[1753/2129] Selena Gomez - Same Old Love
[1754/2129] Selena Gomez - Single Soon
[1755/2129] Selena Gomez - Slow Down
[1756/2129] Selena Gomez - The Heart Wants What It Wants
[1757/2129] Sexyy Red & Bruno Mars - Fat Juicy & Wet
[1758/2129] Shaboozey - A Bar Song (Tipsy)
[1759/2129] Shaboozey - Good News
[1760/2129] SHAED - Trampoline
[1761/2129] Shaggy Featuring Mohombi, Faydee, Costi - I Need Your Love
[1762/2129] Shaggy Featuring Pitbull & Gene Noble - Only Love
[1763/2129] Shakira Featuring Rihanna - Can't Remember To Forget You
[1764/2129] Shakira - Empire
[1765/2129] Shakira Featuring Lil Wayne - Give It Up To Me
[1766/2129] Shakira - She Wolf
[1767/2129] Shawn Hook - Sound Of Your Heart
[1768/2129] Shawn Mendes & Camila Cabello - I Know What You Did Last Summer
[1769/2129] Shawn Mendes & Tainy - Summer Of Love
[1770/2129] Shawn Mendes - If I Can't Have You
[1771/2129] Shawn Mendes - In My Blood
[1772/2129] Shawn Mendes - Mercy
[1773/2129] Shawn Mendes - Stitches
[1774/2129] Shawn Mendes - There's Nothing Holdin' Me Back
[1775/2129] Shawn Mendes - Treat You Better
[1776/2129] Shawn Mendes - When You're Gone
[1777/2129] Shawn Mendes - Why Why Why
[1778/2129] Shawn Mendes - Wonder
[1779/2129] Sheppard - Geronimo
[1780/2129] Shinedown - A Symptom Of Being Human
[1781/2129] Shinedown - If You Only Knew
[1782/2129] Shinedown - Second Chance
[1783/2129] Shinedown - Three Six Five
[1784/2129] Shontelle - Impossible
[1785/2129] Shontelle - Say Hello To Goodbye
[1786/2129] Shontelle - T-Shirt
[1787/2129] Sia - Chandelier
[1788/2129] Sia - Elastic Heart
[1789/2129] Sia Featuring Kendrick Lamar - The Greatest
[1790/2129] Sia - Together
[1791/2129] Sia - Unstoppable
[1792/2129] Sick Puppies - Maybe
[1793/2129] Sienna Spiro - Die On This Hill
[1794/2129] Sigala. & James Arthur - Lasting Lover
[1795/2129] Silk Sonic (Bruno Mars & Anderson .Paak) - Leave The Door Open
[1796/2129] Silk Sonic (Bruno Mars & Anderson .Paak) - Skate
[1797/2129] Silk Sonic (Bruno Mars & Anderson .Paak) - Smokin Out The Window
[1798/2129] Simple Plan - Your Love Is A Lie
[1799/2129] SKINZ - Poison Ivy
[1800/2129] Skylar Grey Featuring Eminem - C'mon Let Me Ride
[1801/2129] Slayyyter - Dance...
[1802/2129] SMITH - Halloween Song
[1803/2129] SMITH - Lobby
[1804/2129] SMITH - Pathetic
[1805/2129] SMITH - Run
[1806/2129] Snoop Dogg & Wiz Khalifa Featuring Bruno Mars - Young, Wild & Free
[1807/2129] Snoop Dogg Featuring The-Dream - Gangsta Luv
[1808/2129] Snoop Dogg - Sensual Seduction
[1809/2129] Sofia Carson - Fool's Gold
[1810/2129] sombr - 12 To 12
[1811/2129] sombr - Back To Friends
[1812/2129] sombr - Homewrecker
[1813/2129] sombr - My Body Isn't Ready
[1814/2129] sombr - Undressed
[1815/2129] Sophie Ellis-Bextor - Murder On The Dancefloor
[1816/2129] Soulja Boy Tell'em - Crank That (Soulja Boy)
[1817/2129] Spose - I'm Awesome
[1818/2129] Stargate Featuring P!nk & Sia - Waterfall
[1819/2129] Starley - Call On Me
[1820/2129] Stella Lefty - Boston
[1821/2129] Stephen Puth - Look Away
[1822/2129] Stephen Sanchez - Until I Found You
[1823/2129] Steve Aoki, Chris Lake & Tujamo Featuring Kid Ink - Delirious (Boneless)
[1824/2129] Steve Aoki Featuring BTS - Waste It On Me
[1825/2129] Steve Lacy - Bad Habit
[1826/2129] Steven Malcolm, KB & for KING + COUNTRY - Yes
[1827/2129] Steven Tyler - (It) Feels So Good
[1828/2129] Surfaces - Sunday Best
[1829/2129] Swedish House Mafia & The Weeknd - Moth To A Flame
[1830/2129] Swedish House Mafia Featuring John Martin - Don't You Worry Child
[1831/2129] Swedish House Mafia - Save The World
[1832/2129] SZA - BMF
[1833/2129] SZA - Good Days
[1834/2129] SZA - I Hate U
[1835/2129] SZA - Kill Bill
[1836/2129] SZA - Nobody Gets Me
[1837/2129] SZA - Saturn
[1838/2129] SZA - Snooze
[1839/2129] T-Pain Featuring Wiz Khalifa & Lily Allen - 5 O'Clock
[1840/2129] T-Pain Featuring Chris Brown - Best Love Song
[1841/2129] T-Pain Featuring Lil Wayne - Can't Believe It
[1842/2129] Taemin - Long Way Home
[1843/2129] Tai Verdes - A-O-K
[1844/2129] Taio Cruz Featuring Ludacris - Break Your Heart
[1845/2129] Taio Cruz Featuring Ke$ha - Dirty Picture
[1846/2129] Taio Cruz - Dynamite
[1847/2129] Taio Cruz Featuring Flo Rida - Hangover
[1848/2129] Tate McRae - Exes
[1849/2129] Tate McRae - Greedy
[1850/2129] Tate McRae - It's Ok I'm Ok
[1851/2129] Tate McRae - Revolving Door
[1852/2129] Tate McRae - She's All I Wanna Be
[1853/2129] Tate McRae - Sports Car
[1854/2129] Tate McRae - Tit For Tat
[1855/2129] Tate McRae - You Broke Me First.
[1856/2129] Taylor Swift - All Of The Girls You Loved Before
[1857/2129] Taylor Swift - Anti-Hero
[1858/2129] Taylor Swift - Back To December
[1859/2129] Taylor Swift - Blank Space
[1860/2129] Taylor Swift - Cardigan
[1861/2129] Taylor Swift - Cruel Summer
[1862/2129] Taylor Swift - Delicate
[1863/2129] Taylor Swift - Elizabeth Taylor
[1864/2129] Taylor Swift Featuring Ed Sheeran - Everything Has Changed
[1865/2129] Taylor Swift - Eyes Open
[1866/2129] Taylor Swift - Fifteen
[1867/2129] Taylor Swift - I Can Do It With A Broken Heart
[1868/2129] Taylor Swift - I Knew It, I Knew You
[1869/2129] Taylor Swift - I Knew You Were Trouble.
[1870/2129] Taylor Swift - Is It Over Now? (Taylor's Version) [From The Vault]
[1871/2129] Taylor Swift - Karma
[1872/2129] Taylor Swift - Lavender Haze
[1873/2129] Taylor Swift - Look What You Made Me Do
[1874/2129] Taylor Swift - Love Story
[1875/2129] Taylor Swift - Lover
[1876/2129] Taylor Swift - Message In A Bottle (Taylor's Version) (From The Vault)
[1877/2129] Taylor Swift - Mine
[1878/2129] Taylor Swift - My Boy Only Breaks His Favorite Toys
[1879/2129] Taylor Swift - New Romantics
[1880/2129] Taylor Swift - Opalite
[1881/2129] Taylor Swift - Our Song
[1882/2129] Taylor Swift - Out Of The Woods
[1883/2129] Taylor Swift - ...Ready For It?
[1884/2129] Taylor Swift - Shake It Off
[1885/2129] Taylor Swift - Style
[1886/2129] Taylor Swift - Teardrops On My Guitar
[1887/2129] Taylor Swift - The Fate Of Ophelia
[1888/2129] Taylor Swift Featuring Sabrina Carpenter - The Life Of A Showgirl
[1889/2129] Taylor Swift - The Man
[1890/2129] Taylor Swift - The Story Of Us
[1891/2129] Taylor Swift - Today Was A Fairytale
[1892/2129] Taylor Swift - We Are Never Ever Getting Back Together
[1893/2129] Taylor Swift - Wi$h Li$t
[1894/2129] Taylor Swift - Wildest Dreams
[1895/2129] Taylor Swift - Willow
[1896/2129] Taylor Swift - You Belong With Me
[1897/2129] Taylor Swift - You Need To Calm Down
[1898/2129] Teddy Swims - Bad Dreams
[1899/2129] Teddy Swims - Lose Control
[1900/2129] Teddy Swims - Mr. Know It All
[1901/2129] Teddy Swims - The Door
[1902/2129] Tegan and Sara - Closer
[1903/2129] The 1975 - Chocolate
[1904/2129] The 1975 - Girls
[1905/2129] The 1975 - The Sound
[1906/2129] The All-American Rejects - Beekeeper's Daughter
[1907/2129] The All-American Rejects - Gives You Hell
[1908/2129] The All-American Rejects - I Wanna
[1909/2129] The All-American Rejects - The Wind Blows
[1910/2129] THE ANXIETY: WILLOW & Tyler Cole - Meet Me At Our Spot
[1911/2129] The Band Perry - If I Die Young
[1912/2129] The Beaches - Blame Brett
[1913/2129] The Beaches - Edge Of The Earth
[1914/2129] The Chainsmokers Featuring 5 Seconds of Summer - Who Do You Love
[1915/2129] The Chainsmokers & Bebe Rexha - Call You Mine
[1916/2129] The Chainsmokers Featuring Daya - Don't Let Me Down
[1917/2129] The Chainsmokers - Everybody Hates Me
[1918/2129] The Chainsmokers - High
[1919/2129] The Chainsmokers - Honest
[1920/2129] The Chainsmokers - Paris
[1921/2129] The Chainsmokers - #SELFIE
[1922/2129] The Chainsmokers Featuring Emily Warren - Side Effects
[1923/2129] The-Dream - I Luv Your Girl
[1924/2129] The Fray - Heartbeat
[1925/2129] The Fray - Never Say Never
[1926/2129] The Fray - Syndicate
[1927/2129] The Fray - You Found Me
[1928/2129] The Kid Laroi - Girls
[1929/2129] The Kid Laroi - Love Again
[1930/2129] The Kid Laroi - So Done
[1931/2129] The Kid Laroi - Thousand Miles
[1932/2129] The Kid Laroi - Without You
[1933/2129] The Killers - Human
[1934/2129] The Lumineers - Ho Hey
[1935/2129] The Madden Brothers - We Are Done
[1936/2129] The Neighbourhood - Sweater Weather
[1937/2129] The Pussycat Dolls - I Hate This Part
[1938/2129] The Pussycat Dolls - When I Grow Up
[1939/2129] The Ready Set - Give Me Your Hand (Best Song Ever)
[1940/2129] The Ready Set - Love Like Woe
[1941/2129] The Ready Set - Young Forever
[1942/2129] THE SCOTTS, Travis Scott & Kid Cudi - The Scotts
[1943/2129] The Script - Breakeven
[1944/2129] The Script - For The First Time
[1945/2129] The Script Featuring will.i.am - Hall Of Fame
[1946/2129] The Script - Nothing
[1947/2129] The Script - The Man Who Can't Be Moved
[1948/2129] The Spill Canvas - All Over You
[1949/2129] The Ting Tings - Shut Up And Let Me Go
[1950/2129] The Ting Tings - That's Not My Name
[1951/2129] The Veronicas - Untouched
[1952/2129] The Walters - I Love You So
[1953/2129] The Wanted - Chasing The Sun
[1954/2129] The Wanted - Glad You Came
[1955/2129] The Weeknd - Blinding Lights
[1956/2129] The Weeknd - Can't Feel My Face
[1957/2129] The Weeknd - Cry For Me
[1958/2129] The Weeknd - Dancing In The Flames
[1959/2129] The Weeknd - Die For You
[1960/2129] The Weeknd - Heartless
[1961/2129] The Weeknd Featuring Daft Punk - I Feel It Coming
[1962/2129] The Weeknd - In The Night
[1963/2129] The Weeknd - In Your Eyes
[1964/2129] The Weeknd - Out Of Time
[1965/2129] The Weeknd - Sacrifice
[1966/2129] The Weeknd - Save Your Tears
[1967/2129] The Weeknd - Take My Breath
[1968/2129] The Weeknd - The Hills
[1969/2129] The White Tie Affair - Candle (Sick And Tired)
[1970/2129] The White Tie Affair - You Look Better When I'm Drunk
[1971/2129] Theory Of A Deadman - All Or Nothing
[1972/2129] Theory Of A Deadman - Not Meant To Be
[1973/2129] Thirty Seconds To Mars - Closer To The Edge
[1974/2129] Thirty Seconds To Mars - Seasons
[1975/2129] Thirty Seconds To Mars - Walk On Water
[1976/2129] Three Days Grace - Never Too Late
[1977/2129] Thriving Ivory - Angels On The Moon
[1978/2129] T.I. Featuring Justin Timberlake - Dead And Gone
[1979/2129] T.I. - Whatever You Like
[1980/2129] Timbaland Featuring OneRepublic - Apologize
[1981/2129] Timbaland Featuring Justin Timberlake - Carry Out
[1982/2129] Timbaland Featuring Katy Perry - If We Ever Meet Again
[1983/2129] Timbaland, Nelly Furtado & Justin Timberlake - Keep Going Up!
[1984/2129] Timbaland Featuring Pitbull - Pass At Me
[1985/2129] Timbaland Featuring Keri Hilson - The Way I Are
[1986/2129] Timeflies - Once In A While
[1987/2129] Tina Parol - Who's Got Your Money?
[1988/2129] Tinashe - Nasty
[1989/2129] Tinashe Featuring Chris Brown - Player
[1990/2129] Tinie Tempah Featuring Zara Larsson - Girls Like
[1991/2129] Tinie Tempah Featuring Wiz Khalifa - Till I'm Gone
[1992/2129] Tinie Tempah Featuring Eric Turner - Written In The Stars
[1993/2129] Tommy Richman - Million Dollar Baby
[1994/2129] TOMORROW X TOGETHER - Magic
[1995/2129] Tones And I - Cloudy Day
[1996/2129] Tones And I - Dance Monkey
[1997/2129] Toosii - Favorite Song
[1998/2129] Topic & A7S - Breaking Me
[1999/2129] Tori Kelly - Hollow
[2000/2129] Tori Kelly - Nobody Love
[2001/2129] Tori Kelly - Should've Been Us
[2002/2129] Tory Lanez - Luv
[2003/2129] Tory Lanez - Say It
[2004/2129] Tove Lo - Cool Girl
[2005/2129] Tove Lo - Habits (Stay High)
[2006/2129] Tove Lo - Talking Body
[2007/2129] Train - 50 Ways To Say Goodbye
[2008/2129] Train - Drive By
[2009/2129] Train - Hey, Soul Sister
[2010/2129] Train - If It's Love
[2011/2129] Train - Marry Me
[2012/2129] Train - Play That Song
[2013/2129] Travie McCoy Featuring Bruno Mars - Billionaire
[2014/2129] Travie McCoy - Need You
[2015/2129] Travie McCoy Featuring Jason Mraz - Rough Water
[2016/2129] Travis Scott - Antidote
[2017/2129] Travis Scott - HIGHEST IN THE ROOM
[2018/2129] Travis Scott - I Know ?
[2019/2129] Travis Scott - Sicko Mode
[2020/2129] Travis Scott - Wake Up
[2021/2129] Trevor Daniel - Alone
[2022/2129] Trevor Daniel - Falling
[2023/2129] Trey Songz Featuring T.I. - 2 Reasons
[2024/2129] Trey Songz Featuring Nicki Minaj - Bottoms Up
[2025/2129] Trey Songz Featuring Fabolous - Say Aah
[2026/2129] Trey Songz - Simply Amazing
[2027/2129] Trey Songz Featuring Nicki Minaj - Touchin, Lovin
[2028/2129] Troye Sivan - Angel Baby
[2029/2129] Troye Sivan - My My My!
[2030/2129] Troye Sivan - One Of Your Girls
[2031/2129] Troye Sivan - Youth
[2032/2129] Twenty One Pilots - Chlorine
[2033/2129] Twenty One Pilots - Heathens
[2034/2129] Twenty One Pilots - Level Of Concern
[2035/2129] Twenty One Pilots - My Blood
[2036/2129] Twenty One Pilots - Ride
[2037/2129] Twenty One Pilots - Saturday
[2038/2129] Twenty One Pilots - Stressed Out
[2039/2129] Twenty One Pilots - The Hype
[2040/2129] Twice - Strategy
[2041/2129] Twice - The Feels
[2042/2129] Tyga, Pop Smoke & Jhene Aiko - Sunshine
[2043/2129] Tyga - Rack City
[2044/2129] Tyga Featuring Offset - Taste
[2045/2129] Tyla - Bliss
[2046/2129] Tyla - Chanel
[2047/2129] Tyla - Push 2 Start
[2048/2129] Tyla Featuring Zara Larsson - She Did It Again
[2049/2129] Tyla - Water
[2050/2129] Tyla Yaweh - Summer Vibes
[2051/2129] Tyler, The Creator - Sugar On My Tongue
[2052/2129] Uncle Kracker - Smile
[2053/2129] Usher, Summer Walker & 21 Savage - Good Good
[2054/2129] Usher - Climax
[2055/2129] Usher Featuring Pitbull - DJ Got Us Fallin' In Love
[2056/2129] Usher Featuring Jay-Z - Hot Tottie
[2057/2129] Usher Featuring Juicy J - I Don't Mind
[2058/2129] Usher - Kissing Strangers
[2059/2129] Usher Featuring Young Jeezy - Love In This Club
[2060/2129] Usher - More
[2061/2129] Usher - Numb
[2062/2129] Usher Featuring will.i.am - OMG
[2063/2129] Usher - Scream
[2064/2129] V Factory - Love Struck
[2065/2129] Vance Joy - Riptide
[2066/2129] V.I.C. - Get Silly
[2067/2129] Victoria Monet - On My Mama
[2068/2129] Waka Flocka Flame - No Hands
[2069/2129] Walk the Moon - One Foot
[2070/2129] Walk the Moon - Shut Up And Dance
[2071/2129] Walker Hayes - Fancy Like
[2072/2129] Wallows - Calling After Me
[2073/2129] We the Kings - Check Yes Juliet (Run Baby Run)
[2074/2129] We the Kings - Heaven Can Wait
[2075/2129] We the Kings - Say You Like Me
[2076/2129] We the Kings - Secret Valentine
[2077/2129] We the Kings Featuring Demi Lovato - We'll Be A Dream
[2078/2129] Webbie Featuring Lil' Phat & Lil' Boosie - Independent
[2079/2129] Weezer - Africa
[2080/2129] Why Don't We - 8 Letters
[2081/2129] Why Don't We - Something Different
[2082/2129] Why Don't We - Trust Fund Baby
[2083/2129] Why Don't We - What Am I
[2084/2129] will.i.am & Nicki Minaj - Check It Out
[2085/2129] will.i.am Featuring Mick Jagger & Jennifer Lopez - T.H.E (The Hardest Ever)
[2086/2129] Willow - Whip My Hair
[2087/2129] Wiz Khalifa - Black And Yellow
[2088/2129] Wiz Khalifa - No Sleep
[2089/2129] Wiz Khalifa - Roll Up
[2090/2129] Wiz Khalifa Featuring Charlie Puth - See You Again
[2091/2129] WizTheMc - Show Me Love
[2092/2129] Wyclef Jean Featuring Akon, Lil Wayne & Niia - Sweetest Girl (Dollar Bill)
[2093/2129] X Ambassadors - Renegades
[2094/2129] X Ambassadors - Unsteady
[2095/2129] XG - Left Right
[2096/2129] Yo Gotti Featuring Nicki Minaj - Rake It Up
[2097/2129] Yolanda Be Cool & Dcup - We No Speak Americano
[2098/2129] Young Money Featuring Lloyd - BedRock
[2099/2129] Young T & Bugsey Featuring Headie One - Don't Rush

,song_id,title,stem_name,candidate_index,start_sec,end_sec,active_ratio,onset_similarity,chroma_similarity,mean_centered_onset_similarity,mean_centered_chroma_similarity,similarity,pitch_class_span,candidate_file
12251,(G)I-DLE - I Do,(G)I-DLE - I Do,bass,0,0.34,8.979977,1.000000,0.674024,0.348757,0.238632,0.198198,0.226502,0.166667,NaN
12260,(G)I-DLE - I Do,(G)I-DLE - I Do,other,0,0.34,8.979977,0.998656,0.940318,0.740520,0.123101,0.309036,0.178881,0.166667,NaN
12252,(G)I-DLE - I Do,(G)I-DLE - I Do,bass,1,2.50,11.139977,1.000000,0.665192,0.362507,0.160030,0.214025,0.176229,0.250000,candidate_000_bass.flac
12261,(G)I-DLE - I Do,(G)I-DLE - I Do,other,1,2.50,11.139977,1.000000,0.942827,0.727999,0.093874,0.287934,0.152092,0.250000,candidate_002_other.flac
12253,(G)I-DLE - I Do,(G)I-DLE - I Do,bass,2,4.66,13.299977,1.000000,0.694816,0.389891,0.191108,0.253314,0.209770,0.166667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32624,will.i.am Featuring Mick Jagger & Jennifer Lop...,will.i.am Featuring Mick Jagger & Jennifer Lop...,bass,7,25.06,34.020000,1.000000,0.456285,0.797375,0.206195,0.614480,0.328680,NaN,NaN
32625,will.i.am Featuring Mick Jagger & Jennifer Lop...,will.i.am Featuring Mick Jagger & Jennifer Lop...,bass,8,26.74,35.700000,1.000000,0.450001,0.588952,0.181251,0.200583,0.187050,NaN,NaN
32626,will.i.am Featuring Mick Jagger & Jennifer Lop...,will.i.am Featuring Mick Jagger & Jennifer Lop...,bass,9,27.30,36.260000,1.000000,0.519632,0.788147,0.275519,0.598617,0.372449,NaN,NaN
32627,will.i.am Featuring Mick Jagger & Jennifer Lop...,will.i.am Featuring Mick Jagger & Jennifer Lop...,bass,10,29.00,37.960000,1.000000,0.435017,0.570255,0.125077,0.167593,0.137832,NaN,NaN
32628,will.i.am Featuring Mick Jagger & Jennifer Lop...,will.i.am Featuring Mick Jagger & Jennifer Lop...,bass,11,29.58,38.540000,1.000000,0.575489,0.779068,0.370710,0.584047,0.434711,0.916667,candidate_002_bass.flac

,track_id,status,reason,output_dir,motif_stem
0,2-pistols-she-got-it,rejected,no_stem_candidate_passed_final_validation,None,None
1,21-savage-redrum,rejected,no_stem_candidate_passed_final_validation,None,None
2,2am-club-worry-about-you,rejected,ValueError: Selected motif mean-centered onset...,None,None
3,3-doors-down-its-not-my-time,rejected,no_stem_candidate_passed_final_validation,None,None
4,3oh-3-dont-trust-me-live,rejected,no_stem_candidate_passed_final_validation,None,None
...,...,...,...,...,...
2124,Zedd-maren-morris-and-beauz-make-you-say,accepted,None,/content/drive/MyDrive/MOHIM/motif_dataset_mea...,other
2125,Zedd-spectrum,rejected,no_stem_candidate_passed_final_validation,None,None
2126,Zendaya-replay,rejected,no_candidate_passed_export_filters,None,None
2127,Zendaya-something-new,accepted,None,/content/drive/MyDrive/MOHIM/motif_dataset_mea...,other
2128,Zoe-wees-control,rejected,no_stem_candidate_passed_final_validation,None,None

motif dataset version: /content/drive/MyDrive/MOHIM/motif_dataset_mean_centered/.mohim_motif_version

## 4. 현재 곡의 earliest motif 일괄 재생

현재 입력에 포함된 곡 중 저장된 earliest motif를 `DEBUG_TRACK_INDEX`부터 `DEBUG_TRACK_COUNT`곡씩 표시합니다. 예: 11~20곡은 `DEBUG_TRACK_INDEX = 10`으로 설정합니다.

In [ ]:
from IPython.display import Audio, display

DEBUG_TRACK_INDEX = 0
DEBUG_TRACK_COUNT = 10
selection_paths = []
for song in songs:
    selection_path = (
        DIAGNOSTIC_DIR / diagnostic_song_id(song) / 'motif_selections.json'
    )
    if selection_path.is_file():
        selection_metadata = json.loads(selection_path.read_text(encoding='utf-8'))
        if selection_metadata.get('status') == 'skipped':
            print(f'[skipped] {selection_metadata["title"]}: {selection_metadata["reason"]}')
            continue
        selection_paths.append(selection_path)
assert selection_paths, '현재 곡에 재생 가능한 motif selection이 없습니다.'
selected_paths = selection_paths[
    DEBUG_TRACK_INDEX:DEBUG_TRACK_INDEX + DEBUG_TRACK_COUNT
]
assert selected_paths, (
    f'재생할 곡이 없습니다: start={DEBUG_TRACK_INDEX}, total={len(selection_paths)}'
)

for track_number, selection_path in enumerate(
    selected_paths, start=DEBUG_TRACK_INDEX + 1
):
    selection_metadata = json.loads(selection_path.read_text(encoding='utf-8'))
    row = selection_metadata['selections']['earliest']
    print(f'\n{track_number}. {selection_metadata["title"]}')
    print({key: value for key, value in row.items() if key not in {'candidate_file', 'selection_file'}})
    display(Audio(filename=str(selection_path.parent / row['selection_file'])))

## 5. 선택 motif의 bar별 occurrence 판별

선택된 motif를 query로 삼아 `melodic_accompaniment.flac`의 모든 downbeat를 시작점 후보로 검사합니다. 비교와 최종 mask 구간은 downbeat 간격이 아니라 실제 `selected_earliest.flac` 길이를 사용합니다. 각 downbeat에 raw/mean-centered onset·chroma 점수와 threshold별 통과 여부를 기록하고, 겹치는 양성 window 중 최고점만 canonical occurrence로 남깁니다.

기존 motif 결과에서 occurrence만 볼 때는 0~2번 준비 셀까지만 실행하고 3~4번 추출 셀은 건너뛴 뒤 이 섹션을 실행합니다. `OCCURRENCE_TRACK_QUERY`에 artist/title/folder 일부를 넣으면 해당 곡만 불러옵니다.

In [ ]:
import json
import re
import time
from pathlib import Path
import librosa
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from mohim.motif import _resize_time

OCCURRENCE_HOP_LENGTH = 512
OCCURRENCE_ONSET_N_FFT = 2048
OCCURRENCE_SILENCE_DB = -40.0
MIN_OCCURRENCE_ONSET_SIMILARITY = MIN_ONSET_SIMILARITY
MAX_OCCURRENCE_ONSET_CHROMA_DIFFERENCE = MAX_ONSET_CHROMA_DIFFERENCE
MIN_OCCURRENCE_MEAN_CENTERED_SIMILARITY = MIN_MEAN_CENTERED_SIMILARITY
MIN_OCCURRENCE_ACTIVE_RATIO = MIN_ACTIVE_RATIO
occurrence_analysis_cache = {}

def selected_motif_row(metadata):
    row = metadata.get('selections', {}).get('earliest')
    if row is None:
        raise KeyError('earliest motif selection이 없습니다.')
    return row

def occurrence_safe_folder_name(value):
    cleaned = re.sub(r'[\\/:*?"<>|\x00-\x1f]', '_', value)
    cleaned = re.sub(r'\s+', ' ', cleaned).strip(' .')
    return cleaned[:120] or 'untitled'

assert 'songs' in globals() and 'song_paths' in globals() and song_paths, (
    '1번 입력 셀을 먼저 실행해 songs/song_paths를 준비하세요.'
)
assert len(songs) == len(song_paths), 'songs와 song_paths 길이가 다릅니다.'
selection_paths = []
for song, audio_path in zip(songs, song_paths):
    display_title = (
        f"{song['artist']} - {song['title']}" if song['artist'] else song['title']
    )
    base_name = occurrence_safe_folder_name(display_title)
    short_track_id = occurrence_safe_folder_name(str(song['track_id']))[:8]
    candidates = (
        DIAGNOSTIC_DIR / base_name / 'motif_selections.json',
        DIAGNOSTIC_DIR / f'{base_name[:109]} [{short_track_id}]' / 'motif_selections.json',
    )
    selected_path = None
    for selection_path in candidates:
        if not selection_path.is_file():
            continue
        try:
            metadata = json.loads(selection_path.read_text(encoding='utf-8'))
            source_path = Path(metadata['source_audio'])
            if source_path.resolve() != Path(audio_path).resolve():
                continue
            if metadata.get('status') != 'selected':
                continue
            selection = selected_motif_row(metadata)
            required_paths = (
                selection_path.parent / selection['selection_file'],
                selection_path.parent / 'melodic_accompaniment.flac',
                source_path,
            )
            if all(path.is_file() for path in required_paths):
                selected_path = selection_path
                break
        except (OSError, ValueError, KeyError, TypeError):
            continue
    if selected_path is None:
        print(f'[missing occurrence input] {display_title}')
    else:
        selection_paths.append(selected_path)
assert selection_paths, '현재 song_paths에 occurrence 검수 가능한 selected motif가 없습니다.'
print(f'[occurrence inputs] {len(selection_paths)}곡 / selected songs {len(song_paths)}곡')

def occurrence_shifted_cosine(first, second, *, mean_center):
    scores = []
    for shift in range(-3, 4):
        if shift < 0:
            first_overlap, second_overlap = first[-shift:], second[:shift]
        elif shift > 0:
            first_overlap, second_overlap = first[:-shift], second[shift:]
        else:
            first_overlap, second_overlap = first, second
        if mean_center:
            first_overlap = first_overlap - np.mean(first_overlap)
            second_overlap = second_overlap - np.mean(second_overlap)
        scores.append(float(cosine_similarity(
            first_overlap[None], second_overlap[None]
        )[0, 0]))
    return max(scores)

def occurrence_aligned_chroma_similarities(
    query_raw, query_centered, candidate_raw, candidate_centered,
):
    best = None
    for pitch_shift in range(12):
        shifted_raw = np.roll(candidate_raw, pitch_shift, axis=0)
        shifted_centered = np.roll(candidate_centered, pitch_shift, axis=0)
        for time_shift in (-1, 0, 1):
            if time_shift < 0:
                query_raw_overlap = query_raw[:, :time_shift]
                candidate_raw_overlap = shifted_raw[:, -time_shift:]
                query_centered_overlap = query_centered[:, :time_shift]
                candidate_centered_overlap = shifted_centered[:, -time_shift:]
            elif time_shift > 0:
                query_raw_overlap = query_raw[:, time_shift:]
                candidate_raw_overlap = shifted_raw[:, :-time_shift]
                query_centered_overlap = query_centered[:, time_shift:]
                candidate_centered_overlap = shifted_centered[:, :-time_shift]
            else:
                query_raw_overlap = query_raw
                candidate_raw_overlap = shifted_raw
                query_centered_overlap = query_centered
                candidate_centered_overlap = shifted_centered
            raw_similarity = float(cosine_similarity(
                query_raw_overlap.reshape(1, -1),
                candidate_raw_overlap.reshape(1, -1),
            )[0, 0])
            centered_similarity = float(cosine_similarity(
                query_centered_overlap.reshape(1, -1),
                candidate_centered_overlap.reshape(1, -1),
            )[0, 0])
            result = {
                'raw_similarity': raw_similarity,
                'centered_similarity': centered_similarity,
                'pitch_shift': pitch_shift if pitch_shift <= 6 else pitch_shift - 12,
                'time_shift': time_shift,
            }
            if best is None or (centered_similarity, raw_similarity) > (
                best['centered_similarity'], best['raw_similarity'],
            ):
                best = result
    return best

def occurrence_feature_tracks(audio, sample_rate):
    mono = np.asarray(audio, dtype=np.float32).reshape(-1)
    preroll_frames = OCCURRENCE_ONSET_N_FFT // OCCURRENCE_HOP_LENGTH
    padded = np.pad(mono, (preroll_frames * OCCURRENCE_HOP_LENGTH, 0))
    padded_onset = librosa.onset.onset_strength(
        y=padded, sr=sample_rate, hop_length=OCCURRENCE_HOP_LENGTH,
        n_fft=OCCURRENCE_ONSET_N_FFT,
    )
    rms = librosa.feature.rms(y=mono, hop_length=OCCURRENCE_HOP_LENGTH)[0]
    onset = padded_onset[preroll_frames:preroll_frames + len(rms)]
    chroma = librosa.feature.chroma_cens(
        y=mono, sr=sample_rate, hop_length=OCCURRENCE_HOP_LENGTH
    )
    frame_count = min(len(onset), chroma.shape[1], len(rms))
    rms_db = librosa.amplitude_to_db(rms[:frame_count] + 1e-8, ref=1.0)
    return onset[:frame_count], chroma[:, :frame_count], rms_db

def occurrence_window_features(onset, chroma, rms_db, start_frame, end_frame):
    end_frame = min(end_frame, len(onset), chroma.shape[1], len(rms_db))
    if end_frame - start_frame < 2:
        raise ValueError('occurrence window가 두 frame보다 짧습니다.')
    onset_window = _resize_time(
        onset[None, start_frame:end_frame], 256
    ).ravel()
    raw_chroma = _resize_time(chroma[:, start_frame:end_frame], 64)
    centered_chroma = raw_chroma - np.mean(
        raw_chroma, axis=0, keepdims=True
    )
    active = rms_db[start_frame:end_frame] > OCCURRENCE_SILENCE_DB
    active_ratio = float(np.mean(active)) if len(active) else 0.0
    return (
        onset_window, raw_chroma, centered_chroma, active_ratio
    )

def classify_occurrence_downbeats(
    scores, *, min_onset=MIN_OCCURRENCE_ONSET_SIMILARITY,
    max_difference=MAX_OCCURRENCE_ONSET_CHROMA_DIFFERENCE,
    min_mean_centered=MIN_OCCURRENCE_MEAN_CENTERED_SIMILARITY,
    min_active_ratio=MIN_OCCURRENCE_ACTIVE_RATIO, forced_start_sec=None,
):
    classified = scores.copy()
    classified['active_ratio_pass'] = (
        classified['active_ratio'] >= min_active_ratio
    )
    classified['onset_similarity_pass'] = (
        classified['onset_similarity'] >= min_onset
    )
    classified['onset_chroma_difference_pass'] = (
        classified['onset_chroma_difference'] <= max_difference
    )
    classified['mean_centered_onset_pass'] = (
        classified['mean_centered_onset_similarity'] >= min_mean_centered
    )
    classified['mean_centered_chroma_pass'] = (
        classified['mean_centered_chroma_similarity'] >= min_mean_centered
    )
    pass_columns = [
        'active_ratio_pass', 'onset_similarity_pass',
        'onset_chroma_difference_pass', 'mean_centered_onset_pass',
        'mean_centered_chroma_pass',
    ]
    classified['is_occurrence_candidate'] = classified[pass_columns].all(axis=1)
    classified['is_occurrence'] = classified['is_occurrence_candidate']
    if forced_start_sec is not None:
        forced_index = (
            classified['start_sec'] - float(forced_start_sec)
        ).abs().idxmin()
        classified.at[forced_index, 'is_occurrence'] = True
    return classified

def fill_short_occurrence_gaps(occurrences, *, max_gap_seconds):
    max_gap_seconds = float(max_gap_seconds)
    if max_gap_seconds < 0:
        raise ValueError('max_gap_seconds는 0 이상이어야 합니다.')
    intervals = sorted(
        (
            {
                'start_sec': float(item['start_sec']),
                'end_sec': float(item['end_sec']),
            }
            for item in occurrences
        ),
        key=lambda item: item['start_sec'],
    )
    filled = []
    for interval in intervals:
        if not filled:
            filled.append(interval)
            continue
        gap_seconds = interval['start_sec'] - filled[-1]['end_sec']
        if gap_seconds <= max_gap_seconds:
            filled[-1]['end_sec'] = max(
                filled[-1]['end_sec'], interval['end_sec']
            )
        else:
            filled.append(interval)
    return filled

def rasterize_occurrence_mask(occurrences, *, duration_seconds, frame_count):
    frame_count = int(frame_count)
    if duration_seconds <= 0 or frame_count < 1:
        raise ValueError('duration_seconds와 frame_count는 양수여야 합니다.')
    mask = np.zeros(int(frame_count), dtype=np.float32)
    frames_per_second = frame_count / float(duration_seconds)
    for occurrence in occurrences:
        start = max(0, int(np.floor(
            float(occurrence['start_sec']) * frames_per_second
        )))
        end = min(frame_count, int(np.ceil(
            float(occurrence['end_sec']) * frames_per_second
        )))
        if end > start:
            mask[start:end] = 1.0
    return mask

def json_records(frame):
    return [
        {
            key: value.item() if isinstance(value, np.generic) else value
            for key, value in row.items()
        }
        for row in frame.to_dict(orient='records')
    ]

def occurrence_thresholds():
    return {
        'min_onset_similarity': MIN_OCCURRENCE_ONSET_SIMILARITY,
        'max_onset_chroma_difference':
            MAX_OCCURRENCE_ONSET_CHROMA_DIFFERENCE,
        'min_mean_centered_similarity':
            MIN_OCCURRENCE_MEAN_CENTERED_SIMILARITY,
        'min_active_ratio': MIN_OCCURRENCE_ACTIVE_RATIO,
    }

def compute_motif_occurrence_scores(selection_path, *, force=False):
    selection_path = Path(selection_path)
    cache_key = str(selection_path.resolve())
    if not force and cache_key in occurrence_analysis_cache:
        return occurrence_analysis_cache[cache_key]
    metadata = json.loads(selection_path.read_text(encoding='utf-8'))
    selection = selected_motif_row(metadata)
    song_dir = selection_path.parent
    motif_path = song_dir / selection['selection_file']
    melodic_path = song_dir / 'melodic_accompaniment.flac'
    source_path = Path(metadata['source_audio'])
    for required_path in (motif_path, melodic_path, source_path):
        if not required_path.is_file():
            raise FileNotFoundError(required_path)
    melodic, sample_rate = librosa.load(melodic_path, sr=None, mono=True)
    motif, _ = librosa.load(motif_path, sr=sample_rate, mono=True)
    motif_duration = len(motif) / sample_rate
    full_onset, full_chroma, full_rms_db = occurrence_feature_tracks(
        melodic, sample_rate
    )
    motif_onset, motif_chroma, motif_rms_db = occurrence_feature_tracks(
        motif, sample_rate
    )
    query = occurrence_window_features(
        motif_onset, motif_chroma, motif_rms_db,
        0, min(len(motif_onset), motif_chroma.shape[1], len(motif_rms_db)),
    )
    _, downbeats = beat_tracker(str(source_path))
    downbeats = np.asarray(downbeats, dtype=np.float64).reshape(-1)
    if not len(downbeats):
        raise ValueError(f'downbeat가 없습니다: {metadata["title"]}')
    rows = []
    audio_duration = len(melodic) / sample_rate
    for downbeat_index, downbeat in enumerate(downbeats):
        start_sec = float(downbeat)
        end_sec = start_sec + motif_duration
        if start_sec < 0 or end_sec > audio_duration:
            continue
        start_frame = int(librosa.time_to_frames(
            start_sec, sr=sample_rate, hop_length=OCCURRENCE_HOP_LENGTH
        ))
        end_frame = int(librosa.time_to_frames(
            end_sec, sr=sample_rate, hop_length=OCCURRENCE_HOP_LENGTH
        ))
        try:
            window = occurrence_window_features(
                full_onset, full_chroma, full_rms_db, start_frame, end_frame
            )
        except ValueError:
            continue
        raw_onset = occurrence_shifted_cosine(
            query[0], window[0], mean_center=False
        )
        centered_onset = occurrence_shifted_cosine(
            query[0], window[0], mean_center=True
        )
        chroma_alignment = occurrence_aligned_chroma_similarities(
            query[1], query[2], window[1], window[2]
        )
        raw_chroma = chroma_alignment['raw_similarity']
        centered_chroma = chroma_alignment['centered_similarity']
        rows.append({
            'downbeat_index': downbeat_index,
            'downbeat_number': downbeat_index + 1,
            'start_sec': start_sec,
            'end_sec': end_sec,
            'active_ratio': window[3],
            'onset_similarity': raw_onset,
            'chroma_similarity': raw_chroma,
            'onset_chroma_difference': abs(raw_onset - raw_chroma),
            'mean_centered_onset_similarity': centered_onset,
            'mean_centered_chroma_similarity': centered_chroma,
            'chroma_pitch_shift': chroma_alignment['pitch_shift'],
            'chroma_time_shift': chroma_alignment['time_shift'],
        })
    raw_scores = pd.DataFrame(rows)
    if raw_scores.empty:
        raise ValueError(f'비교할 bar window가 없습니다: {metadata["title"]}')
    anchor_start = float(selection['start_sec'])
    anchor_index = (raw_scores['start_sec'] - anchor_start).abs().idxmin()
    raw_scores['is_selected_anchor'] = False
    raw_scores.at[anchor_index, 'is_selected_anchor'] = True
    scores = classify_occurrence_downbeats(
        raw_scores, forced_start_sec=anchor_start
    )
    occurrence_rows = scores[scores['is_occurrence']].sort_values('start_sec')
    motif_intervals = [
        {
            'downbeat_index': int(row['downbeat_index']),
            'start_sec': float(row['start_sec']),
            'end_sec': float(row['end_sec']),
            'is_selected_anchor': bool(row['is_selected_anchor']),
        }
        for _, row in occurrence_rows.iterrows()
    ]
    max_mask_gap_seconds = 2.0 * motif_duration
    mask_intervals = fill_short_occurrence_gaps(
        motif_intervals, max_gap_seconds=max_mask_gap_seconds
    )
    mask_path = song_dir / 'motif_occurrence_mask.npy'
    occurrence_mask = rasterize_occurrence_mask(
        mask_intervals, duration_seconds=audio_duration,
        frame_count=len(full_onset),
    )
    np.save(mask_path, occurrence_mask)
    output_path = song_dir / 'motif_occurrences.json'
    payload = {
        'schema': 'mohim_motif_occurrence_mask_v2',
        'song_id': metadata['song_id'],
        'title': metadata['title'],
        'source_audio': metadata['source_audio'],
        'selection_file': selection['selection_file'],
        'motif_start_sec': anchor_start,
        'motif_end_sec': anchor_start + motif_duration,
        'motif_duration_seconds': motif_duration,
        'duration_seconds': audio_duration,
        'motif_bars': MOTIF_BARS,
        'mask_semantics': (
            '1 inside detected motif intervals and internal gaps no longer than '
            '2x motif duration, 0 elsewhere'
        ),
        'mask_fill_max_gap_seconds': max_mask_gap_seconds,
        'thresholds': occurrence_thresholds(),
        'downbeat_candidate_count': len(scores),
        'occurrence_candidate_count': int(scores['is_occurrence_candidate'].sum()),
        'occurrence_count': int(scores['is_occurrence'].sum()),
        'downbeat_scores': json_records(scores),
        'motif_intervals': motif_intervals,
        'mask_intervals': mask_intervals,
        'mask_file': mask_path.name,
        'mask_frame_count': len(occurrence_mask),
        'mask_sample_rate': sample_rate,
        'mask_hop_length': OCCURRENCE_HOP_LENGTH,
        'mask_frame_rate': sample_rate / OCCURRENCE_HOP_LENGTH,
    }
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8'
    )
    assert bool(scores.loc[anchor_index, 'is_occurrence'])
    result = {
        'metadata': metadata, 'selection': selection, 'scores': scores,
        'motif_path': motif_path, 'melodic_path': melodic_path,
        'source_path': source_path, 'output_path': output_path,
        'mask_path': mask_path, 'occurrence_mask': occurrence_mask,
        'motif_duration': motif_duration, 'audio_duration': audio_duration,
        'motif_intervals': motif_intervals, 'mask_intervals': mask_intervals,
    }
    occurrence_analysis_cache[cache_key] = result
    return result

def format_duration(seconds):
    minutes, seconds = divmod(max(0.0, float(seconds)), 60.0)
    return f'{int(minutes):02d}:{seconds:04.1f}'

def compute_all_motif_occurrences(paths, *, force=False):
    started_at = time.monotonic()
    all_occurrence_rows = []
    failures = []
    total = len(paths)
    for index, selection_path in enumerate(paths, 1):
        elapsed = time.monotonic() - started_at
        eta = elapsed / (index - 1) * (total - index + 1) if index > 1 else None
        eta_text = format_duration(eta) if eta is not None else '계산 중'
        print(f'[occurrence {index}/{total}] ETA {eta_text}: {selection_path.parent.name}')
        try:
            analysis = compute_motif_occurrence_scores(
                selection_path, force=force
            )
        except Exception as error:
            failures.append({
                'selection_path': str(selection_path),
                'error_type': type(error).__name__,
                'error_message': str(error),
            })
            print(f'  [failed] {type(error).__name__}: {error}')
            continue
        rows = analysis['scores'].copy()
        rows.insert(0, 'title', analysis['metadata']['title'])
        rows.insert(0, 'song_id', analysis['metadata']['song_id'])
        all_occurrence_rows.append(rows)
    occurrence_scores_df = (
        pd.concat(all_occurrence_rows, ignore_index=True)
        if all_occurrence_rows else pd.DataFrame()
    )
    if not occurrence_scores_df.empty:
        occurrence_scores_df.to_csv(
            DIAGNOSTIC_DIR / 'all_motif_occurrence_scores.csv', index=False
        )
    failure_path = DIAGNOSTIC_DIR / 'occurrence_failures.jsonl'
    failure_path.write_text(
        ''.join(json.dumps(row, ensure_ascii=False) + '\n' for row in failures),
        encoding='utf-8',
    )
    elapsed = time.monotonic() - started_at
    print(
        f'[occurrence complete] {total - len(failures)}/{total}곡, '
        f'실패 {len(failures)}곡, elapsed {format_duration(elapsed)}'
    )
    return occurrence_scores_df, pd.DataFrame(failures)

RUN_OCCURRENCE_BATCH = False
if RUN_OCCURRENCE_BATCH:
    occurrence_scores_df, occurrence_failures_df = compute_all_motif_occurrences(
        selection_paths
    )
    display(occurrence_scores_df)
    display(occurrence_failures_df)
else:
    print('전체 곡 occurrence 저장은 RUN_OCCURRENCE_BATCH = True로 바꾸고 실행하세요.')

In [ ]:
import ipywidgets as widgets
from IPython.display import HTML

def format_timestamp(seconds):
    minutes, seconds = divmod(float(seconds), 60.0)
    return f'{int(minutes):02d}:{seconds:05.2f}'

def review_motif_occurrences(
    track_index, min_onset, max_difference,
    min_mean_centered, min_active_ratio, audio_count,
):
    analysis = compute_motif_occurrence_scores(selection_paths[int(track_index)])
    scores = classify_occurrence_downbeats(
        analysis['scores'],
        min_onset=min_onset,
        max_difference=max_difference, min_mean_centered=min_mean_centered,
        min_active_ratio=min_active_ratio,
        forced_start_sec=float(analysis['selection']['start_sec']),
    )
    candidates = scores[scores['is_occurrence_candidate']]
    occurrences = scores[scores['is_occurrence']].sort_values('start_sec')
    anchor = float(analysis['selection']['start_sec'])
    display(HTML(f'<h3>{analysis["metadata"]["title"]}</h3>'))
    print(
        f'anchor={format_timestamp(anchor)}, motif length='
        f'{analysis["motif_duration"]:.2f}s, downbeats={len(scores)}, '
        f'candidates={len(candidates)}, occurrences={len(occurrences)}'
    )
    print(f'default 판정 저장 위치: {analysis["output_path"]}')
    display(HTML('<b>Selected 4-bar motif</b>'))
    display(Audio(filename=str(analysis['motif_path'])))
    display(HTML('<b>Original full song</b>'))
    display(Audio(filename=str(analysis['source_path'])))

    preview_rate = 10
    preview_intervals = fill_short_occurrence_gaps(
        json_records(occurrences),
        max_gap_seconds=2.0 * analysis['motif_duration'],
    )
    preview_mask = rasterize_occurrence_mask(
        preview_intervals, duration_seconds=analysis['audio_duration'],
        frame_count=max(1, int(np.ceil(analysis['audio_duration'] * preview_rate))),
    )
    preview_times = np.arange(len(preview_mask)) / preview_rate
    fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)
    axes[0].plot(scores['start_sec'], scores['onset_similarity'], label='raw onset')
    axes[0].plot(scores['start_sec'], scores['chroma_similarity'], label='raw chroma')
    axes[0].axhline(min_onset, color='tab:blue', linestyle=':', label='min onset')
    axes[1].plot(
        scores['start_sec'], scores['mean_centered_onset_similarity'],
        label='mean-centered onset', alpha=0.8,
    )
    axes[1].plot(
        scores['start_sec'], scores['mean_centered_chroma_similarity'],
        label='mean-centered chroma', alpha=0.8,
    )
    axes[2].fill_between(
        preview_times, preview_mask, step='post', color='limegreen', alpha=0.65
    )
    axes[2].set_ylim(-0.05, 1.05)
    axes[2].set_ylabel('motif mask')
    for axis in axes[:2]:
        axis.axvline(anchor, color='red', linestyle='--', linewidth=2)
        for _, row in candidates.iterrows():
            axis.axvspan(row['start_sec'], row['end_sec'], color='gold', alpha=0.08)
        for _, row in occurrences.iterrows():
            axis.axvspan(row['start_sec'], row['end_sec'], color='limegreen', alpha=0.18)
        axis.set_ylim(-0.2, 1.05)
        axis.grid(alpha=0.2)
        axis.legend(loc='lower right')
    axes[0].set_ylabel('raw cosine')
    axes[1].set_ylabel('mean-centered cosine')
    axes[2].set_xlabel('song time (seconds)')
    plt.tight_layout()
    plt.show()

    table = scores.copy()
    table['status'] = np.select(
        [table['is_occurrence'], table['is_occurrence_candidate']],
        ['OCCURRENCE', 'candidate'], default='',
    )
    table['start'] = table['start_sec'].map(format_timestamp)
    table['end'] = table['end_sec'].map(format_timestamp)
    table_columns = [
        'downbeat_number', 'status', 'is_selected_anchor', 'start', 'end', 'active_ratio',
        'onset_similarity', 'chroma_similarity', 'onset_chroma_difference',
        'mean_centered_onset_similarity',
        'mean_centered_chroma_similarity',
    ]
    display(table[table_columns].style.format({
        column: '{:.3f}'
        for column in table_columns
        if column not in {'downbeat_number', 'status', 'is_selected_anchor', 'start', 'end'}
    }))

    if occurrences.empty or audio_count == 0:
        print('재생할 canonical occurrence가 없습니다. threshold를 조정하세요.')
        return
    full_mix, full_sr = librosa.load(analysis['source_path'], sr=None, mono=True)
    melodic, melodic_sr = librosa.load(analysis['melodic_path'], sr=None, mono=True)
    for number, (_, occurrence) in enumerate(
        occurrences.head(int(audio_count)).iterrows(), 1
    ):
        clip_start = max(0.0, float(occurrence['start_sec']) - 1.0)
        clip_end = float(occurrence['end_sec']) + 1.0
        display(HTML(
            f'<h4>{number}. downbeat {int(occurrence["downbeat_number"])} | '
            f'{format_timestamp(occurrence["start_sec"])} | '
            f'score={occurrence["similarity"]:.3f}</h4>'
        ))
        print('full mix (+/- 1s context)')
        display(Audio(
            full_mix[int(clip_start * full_sr):int(clip_end * full_sr)], rate=full_sr
        ))
        print('melodic accompaniment (+/- 1s context)')
        display(Audio(
            melodic[int(clip_start * melodic_sr):int(clip_end * melodic_sr)],
            rate=melodic_sr,
        ))

track_options = []
for index, path in enumerate(selection_paths):
    metadata = json.loads(path.read_text(encoding='utf-8'))
    track_options.append((f'{index + 1:04d} | {metadata["title"]}', index))
track_widget = widgets.Dropdown(
    options=track_options, description='곡:', layout=widgets.Layout(width='90%')
)
onset_widget = widgets.FloatSlider(
    value=MIN_OCCURRENCE_ONSET_SIMILARITY, min=0.0, max=1.0, step=0.01,
    description='raw onset:', continuous_update=False,
)
difference_widget = widgets.FloatSlider(
    value=MAX_OCCURRENCE_ONSET_CHROMA_DIFFERENCE, min=0.0, max=1.0, step=0.01,
    description='raw 차이:', continuous_update=False,
)
centered_widget = widgets.FloatSlider(
    value=MIN_OCCURRENCE_MEAN_CENTERED_SIMILARITY, min=-0.1, max=1.0, step=0.01,
    description='centered:', continuous_update=False,
)
active_widget = widgets.FloatSlider(
    value=MIN_OCCURRENCE_ACTIVE_RATIO, min=0.0, max=1.0, step=0.01,
    description='active:', continuous_update=False,
)
audio_widget = widgets.IntSlider(
    value=4, min=0, max=20, step=1, description='재생 개수:',
    continuous_update=False,
)
review_output = widgets.interactive_output(
    review_motif_occurrences,
    {
        'track_index': track_widget,
        'min_onset': onset_widget, 'max_difference': difference_widget,
        'min_mean_centered': centered_widget, 'min_active_ratio': active_widget,
        'audio_count': audio_widget,
    },
)
display(widgets.VBox([
    track_widget, onset_widget, difference_widget, centered_widget,
    active_widget, audio_widget,
]), review_output)